// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentImportReferrer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentImportReferrer{}

// EnvironmentImportReferrer An EnvironmentImportReferrer represents an `import` reference from another environment.
type EnvironmentImportReferrer struct {
	// The name of the referring environment.
	Name string `json:"name"`
	// The project name of the referring environment.
	Project string `json:"project"`
	// The revision number of the referring environment.
	Revision int64 `json:"revision"`
}

type _EnvironmentImportReferrer EnvironmentImportReferrer

// NewEnvironmentImportReferrer instantiates a new EnvironmentImportReferrer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentImportReferrer(name string, project string, revision int64) *EnvironmentImportReferrer {
	this := EnvironmentImportReferrer{}
	this.Name = name
	this.Project = project
	this.Revision = revision
	return &this
}

// NewEnvironmentImportReferrerWithDefaults instantiates a new EnvironmentImportReferrer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentImportReferrerWithDefaults() *EnvironmentImportReferrer {
	this := EnvironmentImportReferrer{}
	return &this
}

// GetName returns the Name field value
func (o *EnvironmentImportReferrer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnvironmentImportReferrer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnvironmentImportReferrer) SetName(v string) {
	o.Name = v
}

// GetProject returns the Project field value
func (o *EnvironmentImportReferrer) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *EnvironmentImportReferrer) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *EnvironmentImportReferrer) SetProject(v string) {
	o.Project = v
}

// GetRevision returns the Revision field value
func (o *EnvironmentImportReferrer) GetRevision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *EnvironmentImportReferrer) GetRevisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *EnvironmentImportReferrer) SetRevision(v int64) {
	o.Revision = v
}

func (o EnvironmentImportReferrer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentImportReferrer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["project"] = o.Project
	toSerialize["revision"] = o.Revision
	return toSerialize, nil
}

func (o *EnvironmentImportReferrer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"project",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentImportReferrer := _EnvironmentImportReferrer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentImportReferrer)

	if err != nil {
		return err
	}

	*o = EnvironmentImportReferrer(varEnvironmentImportReferrer)

	return err
}

type NullableEnvironmentImportReferrer struct {
	value *EnvironmentImportReferrer
	isSet bool
}

func (v NullableEnvironmentImportReferrer) Get() *EnvironmentImportReferrer {
	return v.value
}

func (v *NullableEnvironmentImportReferrer) Set(val *EnvironmentImportReferrer) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentImportReferrer) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentImportReferrer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentImportReferrer(val *EnvironmentImportReferrer) *NullableEnvironmentImportReferrer {
	return &NullableEnvironmentImportReferrer{value: val, isSet: true}
}

func (v NullableEnvironmentImportReferrer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentImportReferrer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


