// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentStackReferrer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentStackReferrer{}

// EnvironmentStackReferrer An EnvironmentStackReferrer represents a reference from an IaC stack.
type EnvironmentStackReferrer struct {
	// The project name of the referring stack.
	Project string `json:"project"`
	// The name of the referring stack.
	Stack string `json:"stack"`
	// The version of the stack update that references this environment.
	Version int64 `json:"version"`
}

type _EnvironmentStackReferrer EnvironmentStackReferrer

// NewEnvironmentStackReferrer instantiates a new EnvironmentStackReferrer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentStackReferrer(project string, stack string, version int64) *EnvironmentStackReferrer {
	this := EnvironmentStackReferrer{}
	this.Project = project
	this.Stack = stack
	this.Version = version
	return &this
}

// NewEnvironmentStackReferrerWithDefaults instantiates a new EnvironmentStackReferrer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentStackReferrerWithDefaults() *EnvironmentStackReferrer {
	this := EnvironmentStackReferrer{}
	return &this
}

// GetProject returns the Project field value
func (o *EnvironmentStackReferrer) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *EnvironmentStackReferrer) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *EnvironmentStackReferrer) SetProject(v string) {
	o.Project = v
}

// GetStack returns the Stack field value
func (o *EnvironmentStackReferrer) GetStack() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stack
}

// GetStackOk returns a tuple with the Stack field value
// and a boolean to check if the value has been set.
func (o *EnvironmentStackReferrer) GetStackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stack, true
}

// SetStack sets field value
func (o *EnvironmentStackReferrer) SetStack(v string) {
	o.Stack = v
}

// GetVersion returns the Version field value
func (o *EnvironmentStackReferrer) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *EnvironmentStackReferrer) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *EnvironmentStackReferrer) SetVersion(v int64) {
	o.Version = v
}

func (o EnvironmentStackReferrer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentStackReferrer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project"] = o.Project
	toSerialize["stack"] = o.Stack
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *EnvironmentStackReferrer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project",
		"stack",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentStackReferrer := _EnvironmentStackReferrer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentStackReferrer)

	if err != nil {
		return err
	}

	*o = EnvironmentStackReferrer(varEnvironmentStackReferrer)

	return err
}

type NullableEnvironmentStackReferrer struct {
	value *EnvironmentStackReferrer
	isSet bool
}

func (v NullableEnvironmentStackReferrer) Get() *EnvironmentStackReferrer {
	return v.value
}

func (v *NullableEnvironmentStackReferrer) Set(val *EnvironmentStackReferrer) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentStackReferrer) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentStackReferrer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentStackReferrer(val *EnvironmentStackReferrer) *NullableEnvironmentStackReferrer {
	return &NullableEnvironmentStackReferrer{value: val, isSet: true}
}

func (v NullableEnvironmentStackReferrer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentStackReferrer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


