// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckEnvironmentResponse{}

// CheckEnvironmentResponse struct for CheckEnvironmentResponse
type CheckEnvironmentResponse struct {
	ExecutionContext *EscEvaluatedExecutionContext `json:"executionContext,omitempty"`
	// Exprs contains the AST for each expression in the environment definition.
	Exprs *map[string]EscExpr `json:"exprs,omitempty"`
	// Properties contains the detailed values produced by the environment.
	Properties *map[string]EscValue `json:"properties,omitempty"`
	// Schema contains the schema for Properties.
	Schema interface{} `json:"schema,omitempty"`
	// List of diagnostics
	Diagnostics []EnvironmentDiagnostic `json:"diagnostics,omitempty"`
	EnvironmentFunctionSummary EnvironmentFunctionSummary `json:"environmentFunctionSummary"`
}

type _CheckEnvironmentResponse CheckEnvironmentResponse

// NewCheckEnvironmentResponse instantiates a new CheckEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckEnvironmentResponse(environmentFunctionSummary EnvironmentFunctionSummary) *CheckEnvironmentResponse {
	this := CheckEnvironmentResponse{}
	this.EnvironmentFunctionSummary = environmentFunctionSummary
	return &this
}

// NewCheckEnvironmentResponseWithDefaults instantiates a new CheckEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckEnvironmentResponseWithDefaults() *CheckEnvironmentResponse {
	this := CheckEnvironmentResponse{}
	return &this
}

// GetExecutionContext returns the ExecutionContext field value if set, zero value otherwise.
func (o *CheckEnvironmentResponse) GetExecutionContext() EscEvaluatedExecutionContext {
	if o == nil || IsNil(o.ExecutionContext) {
		var ret EscEvaluatedExecutionContext
		return ret
	}
	return *o.ExecutionContext
}

// GetExecutionContextOk returns a tuple with the ExecutionContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckEnvironmentResponse) GetExecutionContextOk() (*EscEvaluatedExecutionContext, bool) {
	if o == nil || IsNil(o.ExecutionContext) {
		return nil, false
	}
	return o.ExecutionContext, true
}

// HasExecutionContext returns a boolean if a field has been set.
func (o *CheckEnvironmentResponse) HasExecutionContext() bool {
	if o != nil && !IsNil(o.ExecutionContext) {
		return true
	}

	return false
}

// SetExecutionContext gets a reference to the given EscEvaluatedExecutionContext and assigns it to the ExecutionContext field.
func (o *CheckEnvironmentResponse) SetExecutionContext(v EscEvaluatedExecutionContext) {
	o.ExecutionContext = &v
}

// GetExprs returns the Exprs field value if set, zero value otherwise.
func (o *CheckEnvironmentResponse) GetExprs() map[string]EscExpr {
	if o == nil || IsNil(o.Exprs) {
		var ret map[string]EscExpr
		return ret
	}
	return *o.Exprs
}

// GetExprsOk returns a tuple with the Exprs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckEnvironmentResponse) GetExprsOk() (*map[string]EscExpr, bool) {
	if o == nil || IsNil(o.Exprs) {
		return nil, false
	}
	return o.Exprs, true
}

// HasExprs returns a boolean if a field has been set.
func (o *CheckEnvironmentResponse) HasExprs() bool {
	if o != nil && !IsNil(o.Exprs) {
		return true
	}

	return false
}

// SetExprs gets a reference to the given map[string]EscExpr and assigns it to the Exprs field.
func (o *CheckEnvironmentResponse) SetExprs(v map[string]EscExpr) {
	o.Exprs = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CheckEnvironmentResponse) GetProperties() map[string]EscValue {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]EscValue
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckEnvironmentResponse) GetPropertiesOk() (*map[string]EscValue, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CheckEnvironmentResponse) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]EscValue and assigns it to the Properties field.
func (o *CheckEnvironmentResponse) SetProperties(v map[string]EscValue) {
	o.Properties = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckEnvironmentResponse) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckEnvironmentResponse) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CheckEnvironmentResponse) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *CheckEnvironmentResponse) SetSchema(v interface{}) {
	o.Schema = v
}

// GetDiagnostics returns the Diagnostics field value if set, zero value otherwise.
func (o *CheckEnvironmentResponse) GetDiagnostics() []EnvironmentDiagnostic {
	if o == nil || IsNil(o.Diagnostics) {
		var ret []EnvironmentDiagnostic
		return ret
	}
	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckEnvironmentResponse) GetDiagnosticsOk() ([]EnvironmentDiagnostic, bool) {
	if o == nil || IsNil(o.Diagnostics) {
		return nil, false
	}
	return o.Diagnostics, true
}

// HasDiagnostics returns a boolean if a field has been set.
func (o *CheckEnvironmentResponse) HasDiagnostics() bool {
	if o != nil && !IsNil(o.Diagnostics) {
		return true
	}

	return false
}

// SetDiagnostics gets a reference to the given []EnvironmentDiagnostic and assigns it to the Diagnostics field.
func (o *CheckEnvironmentResponse) SetDiagnostics(v []EnvironmentDiagnostic) {
	o.Diagnostics = v
}

// GetEnvironmentFunctionSummary returns the EnvironmentFunctionSummary field value
func (o *CheckEnvironmentResponse) GetEnvironmentFunctionSummary() EnvironmentFunctionSummary {
	if o == nil {
		var ret EnvironmentFunctionSummary
		return ret
	}

	return o.EnvironmentFunctionSummary
}

// GetEnvironmentFunctionSummaryOk returns a tuple with the EnvironmentFunctionSummary field value
// and a boolean to check if the value has been set.
func (o *CheckEnvironmentResponse) GetEnvironmentFunctionSummaryOk() (*EnvironmentFunctionSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentFunctionSummary, true
}

// SetEnvironmentFunctionSummary sets field value
func (o *CheckEnvironmentResponse) SetEnvironmentFunctionSummary(v EnvironmentFunctionSummary) {
	o.EnvironmentFunctionSummary = v
}

func (o CheckEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExecutionContext) {
		toSerialize["executionContext"] = o.ExecutionContext
	}
	if !IsNil(o.Exprs) {
		toSerialize["exprs"] = o.Exprs
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Diagnostics) {
		toSerialize["diagnostics"] = o.Diagnostics
	}
	toSerialize["environmentFunctionSummary"] = o.EnvironmentFunctionSummary
	return toSerialize, nil
}

func (o *CheckEnvironmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentFunctionSummary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckEnvironmentResponse := _CheckEnvironmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckEnvironmentResponse)

	if err != nil {
		return err
	}

	*o = CheckEnvironmentResponse(varCheckEnvironmentResponse)

	return err
}

type NullableCheckEnvironmentResponse struct {
	value *CheckEnvironmentResponse
	isSet bool
}

func (v NullableCheckEnvironmentResponse) Get() *CheckEnvironmentResponse {
	return v.value
}

func (v *NullableCheckEnvironmentResponse) Set(val *CheckEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckEnvironmentResponse(val *CheckEnvironmentResponse) *NullableCheckEnvironmentResponse {
	return &NullableCheckEnvironmentResponse{value: val, isSet: true}
}

func (v NullableCheckEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


