// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookResponse{}

// WebhookResponse struct for WebhookResponse
type WebhookResponse struct {
	// Whether the webhook is active and will receive deliveries.
	Active bool `json:"active"`
	// The human-readable display name shown in the UI.
	DisplayName string `json:"displayName"`
	// The environment name. Set when the webhook is scoped to a specific environment.
	EnvName *string `json:"envName,omitempty"`
	// Specific event types this webhook subscribes to. If empty, all events are delivered.
	Filters []string `json:"filters,omitempty"`
	// The format of the webhook payload (e.g., 'raw', 'slack', 'ms_teams').
	Format *string `json:"format,omitempty"`
	// Event groups this webhook subscribes to (e.g., 'stacks', 'deployments').
	Groups []string `json:"groups,omitempty"`
	// The unique identifier name for the webhook within its scope.
	Name string `json:"name"`
	// The organization that owns this webhook.
	OrganizationName string `json:"organizationName"`
	// The URL to which webhook payloads are delivered.
	PayloadUrl string `json:"payloadUrl"`
	// The project name. Set when the webhook is scoped to a specific stack.
	ProjectName *string `json:"projectName,omitempty"`
	// Secret will be omitted when returned from the service.
	Secret *string `json:"secret,omitempty"`
	// The stack name. Set when the webhook is scoped to a specific stack.
	StackName *string `json:"stackName,omitempty"`
	// HasSecret is true if the webhook has a secret. This is used to determine whether to show that there is a secret in the UI.
	HasSecretValue bool `json:"hasSecretValue"`
	// SecretCiphertext is the ciphertext value of the webhook's secret. It's used to check whether the secret was changed by the PSP
	SecretCiphertext string `json:"secretCiphertext"`
}

type _WebhookResponse WebhookResponse

// NewWebhookResponse instantiates a new WebhookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookResponse(active bool, displayName string, name string, organizationName string, payloadUrl string, hasSecretValue bool, secretCiphertext string) *WebhookResponse {
	this := WebhookResponse{}
	this.Active = active
	this.DisplayName = displayName
	this.Name = name
	this.OrganizationName = organizationName
	this.PayloadUrl = payloadUrl
	this.HasSecretValue = hasSecretValue
	this.SecretCiphertext = secretCiphertext
	return &this
}

// NewWebhookResponseWithDefaults instantiates a new WebhookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookResponseWithDefaults() *WebhookResponse {
	this := WebhookResponse{}
	return &this
}

// GetActive returns the Active field value
func (o *WebhookResponse) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookResponse) SetActive(v bool) {
	o.Active = v
}

// GetDisplayName returns the DisplayName field value
func (o *WebhookResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *WebhookResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetEnvName returns the EnvName field value if set, zero value otherwise.
func (o *WebhookResponse) GetEnvName() string {
	if o == nil || IsNil(o.EnvName) {
		var ret string
		return ret
	}
	return *o.EnvName
}

// GetEnvNameOk returns a tuple with the EnvName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetEnvNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnvName) {
		return nil, false
	}
	return o.EnvName, true
}

// HasEnvName returns a boolean if a field has been set.
func (o *WebhookResponse) HasEnvName() bool {
	if o != nil && !IsNil(o.EnvName) {
		return true
	}

	return false
}

// SetEnvName gets a reference to the given string and assigns it to the EnvName field.
func (o *WebhookResponse) SetEnvName(v string) {
	o.EnvName = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *WebhookResponse) GetFilters() []string {
	if o == nil || IsNil(o.Filters) {
		var ret []string
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *WebhookResponse) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []string and assigns it to the Filters field.
func (o *WebhookResponse) SetFilters(v []string) {
	o.Filters = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *WebhookResponse) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *WebhookResponse) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *WebhookResponse) SetFormat(v string) {
	o.Format = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *WebhookResponse) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *WebhookResponse) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *WebhookResponse) SetGroups(v []string) {
	o.Groups = v
}

// GetName returns the Name field value
func (o *WebhookResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebhookResponse) SetName(v string) {
	o.Name = v
}

// GetOrganizationName returns the OrganizationName field value
func (o *WebhookResponse) GetOrganizationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *WebhookResponse) SetOrganizationName(v string) {
	o.OrganizationName = v
}

// GetPayloadUrl returns the PayloadUrl field value
func (o *WebhookResponse) GetPayloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayloadUrl
}

// GetPayloadUrlOk returns a tuple with the PayloadUrl field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetPayloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayloadUrl, true
}

// SetPayloadUrl sets field value
func (o *WebhookResponse) SetPayloadUrl(v string) {
	o.PayloadUrl = v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *WebhookResponse) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *WebhookResponse) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *WebhookResponse) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *WebhookResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *WebhookResponse) SetSecret(v string) {
	o.Secret = &v
}

// GetStackName returns the StackName field value if set, zero value otherwise.
func (o *WebhookResponse) GetStackName() string {
	if o == nil || IsNil(o.StackName) {
		var ret string
		return ret
	}
	return *o.StackName
}

// GetStackNameOk returns a tuple with the StackName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetStackNameOk() (*string, bool) {
	if o == nil || IsNil(o.StackName) {
		return nil, false
	}
	return o.StackName, true
}

// HasStackName returns a boolean if a field has been set.
func (o *WebhookResponse) HasStackName() bool {
	if o != nil && !IsNil(o.StackName) {
		return true
	}

	return false
}

// SetStackName gets a reference to the given string and assigns it to the StackName field.
func (o *WebhookResponse) SetStackName(v string) {
	o.StackName = &v
}

// GetHasSecretValue returns the HasSecretValue field value
func (o *WebhookResponse) GetHasSecretValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasSecretValue
}

// GetHasSecretValueOk returns a tuple with the HasSecretValue field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetHasSecretValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasSecretValue, true
}

// SetHasSecretValue sets field value
func (o *WebhookResponse) SetHasSecretValue(v bool) {
	o.HasSecretValue = v
}

// GetSecretCiphertext returns the SecretCiphertext field value
func (o *WebhookResponse) GetSecretCiphertext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretCiphertext
}

// GetSecretCiphertextOk returns a tuple with the SecretCiphertext field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetSecretCiphertextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretCiphertext, true
}

// SetSecretCiphertext sets field value
func (o *WebhookResponse) SetSecretCiphertext(v string) {
	o.SecretCiphertext = v
}

func (o WebhookResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active"] = o.Active
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.EnvName) {
		toSerialize["envName"] = o.EnvName
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	toSerialize["name"] = o.Name
	toSerialize["organizationName"] = o.OrganizationName
	toSerialize["payloadUrl"] = o.PayloadUrl
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.StackName) {
		toSerialize["stackName"] = o.StackName
	}
	toSerialize["hasSecretValue"] = o.HasSecretValue
	toSerialize["secretCiphertext"] = o.SecretCiphertext
	return toSerialize, nil
}

func (o *WebhookResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active",
		"displayName",
		"name",
		"organizationName",
		"payloadUrl",
		"hasSecretValue",
		"secretCiphertext",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookResponse := _WebhookResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookResponse)

	if err != nil {
		return err
	}

	*o = WebhookResponse(varWebhookResponse)

	return err
}

type NullableWebhookResponse struct {
	value *WebhookResponse
	isSet bool
}

func (v NullableWebhookResponse) Get() *WebhookResponse {
	return v.value
}

func (v *NullableWebhookResponse) Set(val *WebhookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookResponse(val *WebhookResponse) *NullableWebhookResponse {
	return &NullableWebhookResponse{value: val, isSet: true}
}

func (v NullableWebhookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


