// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EscExpr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscExpr{}

// EscExpr An Expr holds information about an expression in an environment definition.
type EscExpr struct {
	Access *EscAccessExpr `json:"access,omitempty"`
	Base *EscExpr `json:"base,omitempty"`
	Builtin *EscBuiltinExpr `json:"builtin,omitempty"`
	// The interpolations, if this is a string interpolation expression.
	Interpolate []EscInterpolation `json:"interpolate,omitempty"`
	// Ranges for the object's keys, if this is an object expression.
	KeyRanges *map[string]EscRange `json:"keyRanges,omitempty"`
	// The list elements, if this is a list expression.
	List []EscExpr `json:"list,omitempty"`
	// The literal value, if this is a literal expression (nil, bool, json.Number, or string)
	Literal interface{} `json:"literal,omitempty"`
	// The object properties, if this is an object expression.
	Object *map[string]EscExpr `json:"object,omitempty"`
	Range EscRange `json:"range"`
	// The schema of the expression's result.
	Schema interface{} `json:"schema,omitempty"`
	// The property accessors, if this is a symbol expression.
	Symbol []EscPropertyAccessor `json:"symbol,omitempty"`
}

type _EscExpr EscExpr

// NewEscExpr instantiates a new EscExpr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscExpr(range_ EscRange) *EscExpr {
	this := EscExpr{}
	this.Range = range_
	return &this
}

// NewEscExprWithDefaults instantiates a new EscExpr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscExprWithDefaults() *EscExpr {
	this := EscExpr{}
	return &this
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *EscExpr) GetAccess() EscAccessExpr {
	if o == nil || IsNil(o.Access) {
		var ret EscAccessExpr
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetAccessOk() (*EscAccessExpr, bool) {
	if o == nil || IsNil(o.Access) {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *EscExpr) HasAccess() bool {
	if o != nil && !IsNil(o.Access) {
		return true
	}

	return false
}

// SetAccess gets a reference to the given EscAccessExpr and assigns it to the Access field.
func (o *EscExpr) SetAccess(v EscAccessExpr) {
	o.Access = &v
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *EscExpr) GetBase() EscExpr {
	if o == nil || IsNil(o.Base) {
		var ret EscExpr
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetBaseOk() (*EscExpr, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *EscExpr) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given EscExpr and assigns it to the Base field.
func (o *EscExpr) SetBase(v EscExpr) {
	o.Base = &v
}

// GetBuiltin returns the Builtin field value if set, zero value otherwise.
func (o *EscExpr) GetBuiltin() EscBuiltinExpr {
	if o == nil || IsNil(o.Builtin) {
		var ret EscBuiltinExpr
		return ret
	}
	return *o.Builtin
}

// GetBuiltinOk returns a tuple with the Builtin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetBuiltinOk() (*EscBuiltinExpr, bool) {
	if o == nil || IsNil(o.Builtin) {
		return nil, false
	}
	return o.Builtin, true
}

// HasBuiltin returns a boolean if a field has been set.
func (o *EscExpr) HasBuiltin() bool {
	if o != nil && !IsNil(o.Builtin) {
		return true
	}

	return false
}

// SetBuiltin gets a reference to the given EscBuiltinExpr and assigns it to the Builtin field.
func (o *EscExpr) SetBuiltin(v EscBuiltinExpr) {
	o.Builtin = &v
}

// GetInterpolate returns the Interpolate field value if set, zero value otherwise.
func (o *EscExpr) GetInterpolate() []EscInterpolation {
	if o == nil || IsNil(o.Interpolate) {
		var ret []EscInterpolation
		return ret
	}
	return o.Interpolate
}

// GetInterpolateOk returns a tuple with the Interpolate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetInterpolateOk() ([]EscInterpolation, bool) {
	if o == nil || IsNil(o.Interpolate) {
		return nil, false
	}
	return o.Interpolate, true
}

// HasInterpolate returns a boolean if a field has been set.
func (o *EscExpr) HasInterpolate() bool {
	if o != nil && !IsNil(o.Interpolate) {
		return true
	}

	return false
}

// SetInterpolate gets a reference to the given []EscInterpolation and assigns it to the Interpolate field.
func (o *EscExpr) SetInterpolate(v []EscInterpolation) {
	o.Interpolate = v
}

// GetKeyRanges returns the KeyRanges field value if set, zero value otherwise.
func (o *EscExpr) GetKeyRanges() map[string]EscRange {
	if o == nil || IsNil(o.KeyRanges) {
		var ret map[string]EscRange
		return ret
	}
	return *o.KeyRanges
}

// GetKeyRangesOk returns a tuple with the KeyRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetKeyRangesOk() (*map[string]EscRange, bool) {
	if o == nil || IsNil(o.KeyRanges) {
		return nil, false
	}
	return o.KeyRanges, true
}

// HasKeyRanges returns a boolean if a field has been set.
func (o *EscExpr) HasKeyRanges() bool {
	if o != nil && !IsNil(o.KeyRanges) {
		return true
	}

	return false
}

// SetKeyRanges gets a reference to the given map[string]EscRange and assigns it to the KeyRanges field.
func (o *EscExpr) SetKeyRanges(v map[string]EscRange) {
	o.KeyRanges = &v
}

// GetList returns the List field value if set, zero value otherwise.
func (o *EscExpr) GetList() []EscExpr {
	if o == nil || IsNil(o.List) {
		var ret []EscExpr
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetListOk() ([]EscExpr, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *EscExpr) HasList() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []EscExpr and assigns it to the List field.
func (o *EscExpr) SetList(v []EscExpr) {
	o.List = v
}

// GetLiteral returns the Literal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EscExpr) GetLiteral() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Literal
}

// GetLiteralOk returns a tuple with the Literal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EscExpr) GetLiteralOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Literal) {
		return nil, false
	}
	return &o.Literal, true
}

// HasLiteral returns a boolean if a field has been set.
func (o *EscExpr) HasLiteral() bool {
	if o != nil && IsNil(o.Literal) {
		return true
	}

	return false
}

// SetLiteral gets a reference to the given interface{} and assigns it to the Literal field.
func (o *EscExpr) SetLiteral(v interface{}) {
	o.Literal = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *EscExpr) GetObject() map[string]EscExpr {
	if o == nil || IsNil(o.Object) {
		var ret map[string]EscExpr
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetObjectOk() (*map[string]EscExpr, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *EscExpr) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given map[string]EscExpr and assigns it to the Object field.
func (o *EscExpr) SetObject(v map[string]EscExpr) {
	o.Object = &v
}

// GetRange returns the Range field value
func (o *EscExpr) GetRange() EscRange {
	if o == nil {
		var ret EscRange
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *EscExpr) GetRangeOk() (*EscRange, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Range, true
}

// SetRange sets field value
func (o *EscExpr) SetRange(v EscRange) {
	o.Range = v
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EscExpr) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EscExpr) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *EscExpr) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *EscExpr) SetSchema(v interface{}) {
	o.Schema = v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *EscExpr) GetSymbol() []EscPropertyAccessor {
	if o == nil || IsNil(o.Symbol) {
		var ret []EscPropertyAccessor
		return ret
	}
	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscExpr) GetSymbolOk() ([]EscPropertyAccessor, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *EscExpr) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given []EscPropertyAccessor and assigns it to the Symbol field.
func (o *EscExpr) SetSymbol(v []EscPropertyAccessor) {
	o.Symbol = v
}

func (o EscExpr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscExpr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Access) {
		toSerialize["access"] = o.Access
	}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	if !IsNil(o.Builtin) {
		toSerialize["builtin"] = o.Builtin
	}
	if !IsNil(o.Interpolate) {
		toSerialize["interpolate"] = o.Interpolate
	}
	if !IsNil(o.KeyRanges) {
		toSerialize["keyRanges"] = o.KeyRanges
	}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}
	if o.Literal != nil {
		toSerialize["literal"] = o.Literal
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["range"] = o.Range
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	return toSerialize, nil
}

func (o *EscExpr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEscExpr := _EscExpr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEscExpr)

	if err != nil {
		return err
	}

	*o = EscExpr(varEscExpr)

	return err
}

type NullableEscExpr struct {
	value *EscExpr
	isSet bool
}

func (v NullableEscExpr) Get() *EscExpr {
	return v.value
}

func (v *NullableEscExpr) Set(val *EscExpr) {
	v.value = val
	v.isSet = true
}

func (v NullableEscExpr) IsSet() bool {
	return v.isSet
}

func (v *NullableEscExpr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscExpr(val *EscExpr) *NullableEscExpr {
	return &NullableEscExpr{value: val, isSet: true}
}

func (v NullableEscExpr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscExpr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


