// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the UpdateEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvironmentResponse{}

// UpdateEnvironmentResponse struct for UpdateEnvironmentResponse
type UpdateEnvironmentResponse struct {
	// The list of diagnostics produced by the environment operation.
	Diagnostics []EnvironmentDiagnostic `json:"diagnostics,omitempty"`
}

// NewUpdateEnvironmentResponse instantiates a new UpdateEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentResponse() *UpdateEnvironmentResponse {
	this := UpdateEnvironmentResponse{}
	return &this
}

// NewUpdateEnvironmentResponseWithDefaults instantiates a new UpdateEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvironmentResponseWithDefaults() *UpdateEnvironmentResponse {
	this := UpdateEnvironmentResponse{}
	return &this
}

// GetDiagnostics returns the Diagnostics field value if set, zero value otherwise.
func (o *UpdateEnvironmentResponse) GetDiagnostics() []EnvironmentDiagnostic {
	if o == nil || IsNil(o.Diagnostics) {
		var ret []EnvironmentDiagnostic
		return ret
	}
	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentResponse) GetDiagnosticsOk() ([]EnvironmentDiagnostic, bool) {
	if o == nil || IsNil(o.Diagnostics) {
		return nil, false
	}
	return o.Diagnostics, true
}

// HasDiagnostics returns a boolean if a field has been set.
func (o *UpdateEnvironmentResponse) HasDiagnostics() bool {
	if o != nil && !IsNil(o.Diagnostics) {
		return true
	}

	return false
}

// SetDiagnostics gets a reference to the given []EnvironmentDiagnostic and assigns it to the Diagnostics field.
func (o *UpdateEnvironmentResponse) SetDiagnostics(v []EnvironmentDiagnostic) {
	o.Diagnostics = v
}

func (o UpdateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Diagnostics) {
		toSerialize["diagnostics"] = o.Diagnostics
	}
	return toSerialize, nil
}

type NullableUpdateEnvironmentResponse struct {
	value *UpdateEnvironmentResponse
	isSet bool
}

func (v NullableUpdateEnvironmentResponse) Get() *UpdateEnvironmentResponse {
	return v.value
}

func (v *NullableUpdateEnvironmentResponse) Set(val *UpdateEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvironmentResponse(val *UpdateEnvironmentResponse) *NullableUpdateEnvironmentResponse {
	return &NullableUpdateEnvironmentResponse{value: val, isSet: true}
}

func (v NullableUpdateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


