// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AWSSSOInitiateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AWSSSOInitiateResponse{}

// AWSSSOInitiateResponse Response of the initialization of the AWS SSO flow
type AWSSSOInitiateResponse struct {
	// The auth session id
	SessionId string `json:"sessionId"`
	// The AWS SSO Verification URL
	Url string `json:"url"`
	// The AWS SSO User Code to verify
	UserCode string `json:"userCode"`
}

type _AWSSSOInitiateResponse AWSSSOInitiateResponse

// NewAWSSSOInitiateResponse instantiates a new AWSSSOInitiateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSSSOInitiateResponse(sessionId string, url string, userCode string) *AWSSSOInitiateResponse {
	this := AWSSSOInitiateResponse{}
	this.SessionId = sessionId
	this.Url = url
	this.UserCode = userCode
	return &this
}

// NewAWSSSOInitiateResponseWithDefaults instantiates a new AWSSSOInitiateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSSSOInitiateResponseWithDefaults() *AWSSSOInitiateResponse {
	this := AWSSSOInitiateResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *AWSSSOInitiateResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *AWSSSOInitiateResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *AWSSSOInitiateResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetUrl returns the Url field value
func (o *AWSSSOInitiateResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AWSSSOInitiateResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AWSSSOInitiateResponse) SetUrl(v string) {
	o.Url = v
}

// GetUserCode returns the UserCode field value
func (o *AWSSSOInitiateResponse) GetUserCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserCode
}

// GetUserCodeOk returns a tuple with the UserCode field value
// and a boolean to check if the value has been set.
func (o *AWSSSOInitiateResponse) GetUserCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserCode, true
}

// SetUserCode sets field value
func (o *AWSSSOInitiateResponse) SetUserCode(v string) {
	o.UserCode = v
}

func (o AWSSSOInitiateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AWSSSOInitiateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	toSerialize["url"] = o.Url
	toSerialize["userCode"] = o.UserCode
	return toSerialize, nil
}

func (o *AWSSSOInitiateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
		"url",
		"userCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAWSSSOInitiateResponse := _AWSSSOInitiateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAWSSSOInitiateResponse)

	if err != nil {
		return err
	}

	*o = AWSSSOInitiateResponse(varAWSSSOInitiateResponse)

	return err
}

type NullableAWSSSOInitiateResponse struct {
	value *AWSSSOInitiateResponse
	isSet bool
}

func (v NullableAWSSSOInitiateResponse) Get() *AWSSSOInitiateResponse {
	return v.value
}

func (v *NullableAWSSSOInitiateResponse) Set(val *AWSSSOInitiateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSSSOInitiateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSSSOInitiateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSSSOInitiateResponse(val *AWSSSOInitiateResponse) *NullableAWSSSOInitiateResponse {
	return &NullableAWSSSOInitiateResponse{value: val, isSet: true}
}

func (v NullableAWSSSOInitiateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSSSOInitiateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


