// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the EscEvaluatedExecutionContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscEvaluatedExecutionContext{}

// EscEvaluatedExecutionContext An EvaluatedExecutionContext contains the result of evaluating an execution context passed to the root environment.
type EscEvaluatedExecutionContext struct {
	// Properties contains the detailed values produced by the execution context.
	Properties *map[string]EscValue `json:"properties,omitempty"`
	// Schema contains the schema for Properties.
	Schema interface{} `json:"schema,omitempty"`
}

// NewEscEvaluatedExecutionContext instantiates a new EscEvaluatedExecutionContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscEvaluatedExecutionContext() *EscEvaluatedExecutionContext {
	this := EscEvaluatedExecutionContext{}
	return &this
}

// NewEscEvaluatedExecutionContextWithDefaults instantiates a new EscEvaluatedExecutionContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscEvaluatedExecutionContextWithDefaults() *EscEvaluatedExecutionContext {
	this := EscEvaluatedExecutionContext{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *EscEvaluatedExecutionContext) GetProperties() map[string]EscValue {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]EscValue
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscEvaluatedExecutionContext) GetPropertiesOk() (*map[string]EscValue, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *EscEvaluatedExecutionContext) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]EscValue and assigns it to the Properties field.
func (o *EscEvaluatedExecutionContext) SetProperties(v map[string]EscValue) {
	o.Properties = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EscEvaluatedExecutionContext) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EscEvaluatedExecutionContext) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *EscEvaluatedExecutionContext) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *EscEvaluatedExecutionContext) SetSchema(v interface{}) {
	o.Schema = v
}

func (o EscEvaluatedExecutionContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscEvaluatedExecutionContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableEscEvaluatedExecutionContext struct {
	value *EscEvaluatedExecutionContext
	isSet bool
}

func (v NullableEscEvaluatedExecutionContext) Get() *EscEvaluatedExecutionContext {
	return v.value
}

func (v *NullableEscEvaluatedExecutionContext) Set(val *EscEvaluatedExecutionContext) {
	v.value = val
	v.isSet = true
}

func (v NullableEscEvaluatedExecutionContext) IsSet() bool {
	return v.isSet
}

func (v *NullableEscEvaluatedExecutionContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscEvaluatedExecutionContext(val *EscEvaluatedExecutionContext) *NullableEscEvaluatedExecutionContext {
	return &NullableEscEvaluatedExecutionContext{value: val, isSet: true}
}

func (v NullableEscEvaluatedExecutionContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscEvaluatedExecutionContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


