// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloneEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloneEnvironmentRequest{}

// CloneEnvironmentRequest Request body for cloning an ESC environment to a new environment.
type CloneEnvironmentRequest struct {
	// Name for the newly cloned environment.
	Name string `json:"name"`
	// Whether to copy access control settings from the source environment.
	PreserveAccess *bool `json:"preserveAccess,omitempty"`
	// Whether to copy environment-level tags from the source environment.
	PreserveEnvironmentTags *bool `json:"preserveEnvironmentTags,omitempty"`
	// Whether to copy the revision history from the source environment.
	PreserveHistory *bool `json:"preserveHistory,omitempty"`
	// Whether to copy revision-level tags from the source environment.
	PreserveRevisionTags *bool `json:"preserveRevisionTags,omitempty"`
	// Target project for the cloned environment. If omitted, uses the source project.
	Project *string `json:"project,omitempty"`
	// Specific version of the source environment to clone. If omitted, clones the latest version.
	Version *int64 `json:"version,omitempty"`
}

type _CloneEnvironmentRequest CloneEnvironmentRequest

// NewCloneEnvironmentRequest instantiates a new CloneEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloneEnvironmentRequest(name string) *CloneEnvironmentRequest {
	this := CloneEnvironmentRequest{}
	this.Name = name
	return &this
}

// NewCloneEnvironmentRequestWithDefaults instantiates a new CloneEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloneEnvironmentRequestWithDefaults() *CloneEnvironmentRequest {
	this := CloneEnvironmentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CloneEnvironmentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloneEnvironmentRequest) SetName(v string) {
	o.Name = v
}

// GetPreserveAccess returns the PreserveAccess field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetPreserveAccess() bool {
	if o == nil || IsNil(o.PreserveAccess) {
		var ret bool
		return ret
	}
	return *o.PreserveAccess
}

// GetPreserveAccessOk returns a tuple with the PreserveAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetPreserveAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveAccess) {
		return nil, false
	}
	return o.PreserveAccess, true
}

// HasPreserveAccess returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasPreserveAccess() bool {
	if o != nil && !IsNil(o.PreserveAccess) {
		return true
	}

	return false
}

// SetPreserveAccess gets a reference to the given bool and assigns it to the PreserveAccess field.
func (o *CloneEnvironmentRequest) SetPreserveAccess(v bool) {
	o.PreserveAccess = &v
}

// GetPreserveEnvironmentTags returns the PreserveEnvironmentTags field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetPreserveEnvironmentTags() bool {
	if o == nil || IsNil(o.PreserveEnvironmentTags) {
		var ret bool
		return ret
	}
	return *o.PreserveEnvironmentTags
}

// GetPreserveEnvironmentTagsOk returns a tuple with the PreserveEnvironmentTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetPreserveEnvironmentTagsOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveEnvironmentTags) {
		return nil, false
	}
	return o.PreserveEnvironmentTags, true
}

// HasPreserveEnvironmentTags returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasPreserveEnvironmentTags() bool {
	if o != nil && !IsNil(o.PreserveEnvironmentTags) {
		return true
	}

	return false
}

// SetPreserveEnvironmentTags gets a reference to the given bool and assigns it to the PreserveEnvironmentTags field.
func (o *CloneEnvironmentRequest) SetPreserveEnvironmentTags(v bool) {
	o.PreserveEnvironmentTags = &v
}

// GetPreserveHistory returns the PreserveHistory field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetPreserveHistory() bool {
	if o == nil || IsNil(o.PreserveHistory) {
		var ret bool
		return ret
	}
	return *o.PreserveHistory
}

// GetPreserveHistoryOk returns a tuple with the PreserveHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetPreserveHistoryOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveHistory) {
		return nil, false
	}
	return o.PreserveHistory, true
}

// HasPreserveHistory returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasPreserveHistory() bool {
	if o != nil && !IsNil(o.PreserveHistory) {
		return true
	}

	return false
}

// SetPreserveHistory gets a reference to the given bool and assigns it to the PreserveHistory field.
func (o *CloneEnvironmentRequest) SetPreserveHistory(v bool) {
	o.PreserveHistory = &v
}

// GetPreserveRevisionTags returns the PreserveRevisionTags field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetPreserveRevisionTags() bool {
	if o == nil || IsNil(o.PreserveRevisionTags) {
		var ret bool
		return ret
	}
	return *o.PreserveRevisionTags
}

// GetPreserveRevisionTagsOk returns a tuple with the PreserveRevisionTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetPreserveRevisionTagsOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveRevisionTags) {
		return nil, false
	}
	return o.PreserveRevisionTags, true
}

// HasPreserveRevisionTags returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasPreserveRevisionTags() bool {
	if o != nil && !IsNil(o.PreserveRevisionTags) {
		return true
	}

	return false
}

// SetPreserveRevisionTags gets a reference to the given bool and assigns it to the PreserveRevisionTags field.
func (o *CloneEnvironmentRequest) SetPreserveRevisionTags(v bool) {
	o.PreserveRevisionTags = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *CloneEnvironmentRequest) SetProject(v string) {
	o.Project = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CloneEnvironmentRequest) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloneEnvironmentRequest) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CloneEnvironmentRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *CloneEnvironmentRequest) SetVersion(v int64) {
	o.Version = &v
}

func (o CloneEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloneEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.PreserveAccess) {
		toSerialize["preserveAccess"] = o.PreserveAccess
	}
	if !IsNil(o.PreserveEnvironmentTags) {
		toSerialize["preserveEnvironmentTags"] = o.PreserveEnvironmentTags
	}
	if !IsNil(o.PreserveHistory) {
		toSerialize["preserveHistory"] = o.PreserveHistory
	}
	if !IsNil(o.PreserveRevisionTags) {
		toSerialize["preserveRevisionTags"] = o.PreserveRevisionTags
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *CloneEnvironmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloneEnvironmentRequest := _CloneEnvironmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloneEnvironmentRequest)

	if err != nil {
		return err
	}

	*o = CloneEnvironmentRequest(varCloneEnvironmentRequest)

	return err
}

type NullableCloneEnvironmentRequest struct {
	value *CloneEnvironmentRequest
	isSet bool
}

func (v NullableCloneEnvironmentRequest) Get() *CloneEnvironmentRequest {
	return v.value
}

func (v *NullableCloneEnvironmentRequest) Set(val *CloneEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCloneEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCloneEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloneEnvironmentRequest(val *CloneEnvironmentRequest) *NullableCloneEnvironmentRequest {
	return &NullableCloneEnvironmentRequest{value: val, isSet: true}
}

func (v NullableCloneEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloneEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


