// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentFunctionSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentFunctionSummary{}

// EnvironmentFunctionSummary EnvironmentFunctionSummary summarizes the functions used in an environment, including counts and rotation paths.
type EnvironmentFunctionSummary struct {
	// A map of function names to the number of times they are used.
	FuncCounts map[string]int64 `json:"funcCounts"`
	// The list of paths that have rotation configured.
	RotationPaths []string `json:"rotationPaths"`
}

type _EnvironmentFunctionSummary EnvironmentFunctionSummary

// NewEnvironmentFunctionSummary instantiates a new EnvironmentFunctionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentFunctionSummary(funcCounts map[string]int64, rotationPaths []string) *EnvironmentFunctionSummary {
	this := EnvironmentFunctionSummary{}
	this.FuncCounts = funcCounts
	this.RotationPaths = rotationPaths
	return &this
}

// NewEnvironmentFunctionSummaryWithDefaults instantiates a new EnvironmentFunctionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentFunctionSummaryWithDefaults() *EnvironmentFunctionSummary {
	this := EnvironmentFunctionSummary{}
	return &this
}

// GetFuncCounts returns the FuncCounts field value
func (o *EnvironmentFunctionSummary) GetFuncCounts() map[string]int64 {
	if o == nil {
		var ret map[string]int64
		return ret
	}

	return o.FuncCounts
}

// GetFuncCountsOk returns a tuple with the FuncCounts field value
// and a boolean to check if the value has been set.
func (o *EnvironmentFunctionSummary) GetFuncCountsOk() (*map[string]int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FuncCounts, true
}

// SetFuncCounts sets field value
func (o *EnvironmentFunctionSummary) SetFuncCounts(v map[string]int64) {
	o.FuncCounts = v
}

// GetRotationPaths returns the RotationPaths field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *EnvironmentFunctionSummary) GetRotationPaths() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RotationPaths
}

// GetRotationPathsOk returns a tuple with the RotationPaths field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentFunctionSummary) GetRotationPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.RotationPaths) {
		return nil, false
	}
	return o.RotationPaths, true
}

// SetRotationPaths sets field value
func (o *EnvironmentFunctionSummary) SetRotationPaths(v []string) {
	o.RotationPaths = v
}

func (o EnvironmentFunctionSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentFunctionSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["funcCounts"] = o.FuncCounts
	if o.RotationPaths != nil {
		toSerialize["rotationPaths"] = o.RotationPaths
	}
	return toSerialize, nil
}

func (o *EnvironmentFunctionSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"funcCounts",
		"rotationPaths",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentFunctionSummary := _EnvironmentFunctionSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentFunctionSummary)

	if err != nil {
		return err
	}

	*o = EnvironmentFunctionSummary(varEnvironmentFunctionSummary)

	return err
}

type NullableEnvironmentFunctionSummary struct {
	value *EnvironmentFunctionSummary
	isSet bool
}

func (v NullableEnvironmentFunctionSummary) Get() *EnvironmentFunctionSummary {
	return v.value
}

func (v *NullableEnvironmentFunctionSummary) Set(val *EnvironmentFunctionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentFunctionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentFunctionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentFunctionSummary(val *EnvironmentFunctionSummary) *NullableEnvironmentFunctionSummary {
	return &NullableEnvironmentFunctionSummary{value: val, isSet: true}
}

func (v NullableEnvironmentFunctionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentFunctionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


