// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderSchema{}

// ProviderSchema ProviderSchema describes the input and output schemas for a provider.
type ProviderSchema struct {
	// A description of the provider.
	Description string `json:"description"`
	// The input schema for the provider.
	Inputs interface{} `json:"inputs"`
	// The name of the provider.
	Name string `json:"name"`
	// The output schema for the provider.
	Outputs interface{} `json:"outputs"`
}

type _ProviderSchema ProviderSchema

// NewProviderSchema instantiates a new ProviderSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderSchema(description string, inputs interface{}, name string, outputs interface{}) *ProviderSchema {
	this := ProviderSchema{}
	this.Description = description
	this.Inputs = inputs
	this.Name = name
	this.Outputs = outputs
	return &this
}

// NewProviderSchemaWithDefaults instantiates a new ProviderSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderSchemaWithDefaults() *ProviderSchema {
	this := ProviderSchema{}
	return &this
}

// GetDescription returns the Description field value
func (o *ProviderSchema) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProviderSchema) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProviderSchema) SetDescription(v string) {
	o.Description = v
}

// GetInputs returns the Inputs field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProviderSchema) GetInputs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProviderSchema) GetInputsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return &o.Inputs, true
}

// SetInputs sets field value
func (o *ProviderSchema) SetInputs(v interface{}) {
	o.Inputs = v
}

// GetName returns the Name field value
func (o *ProviderSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProviderSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProviderSchema) SetName(v string) {
	o.Name = v
}

// GetOutputs returns the Outputs field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProviderSchema) GetOutputs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProviderSchema) GetOutputsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return &o.Outputs, true
}

// SetOutputs sets field value
func (o *ProviderSchema) SetOutputs(v interface{}) {
	o.Outputs = v
}

func (o ProviderSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	if o.Inputs != nil {
		toSerialize["inputs"] = o.Inputs
	}
	toSerialize["name"] = o.Name
	if o.Outputs != nil {
		toSerialize["outputs"] = o.Outputs
	}
	return toSerialize, nil
}

func (o *ProviderSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"inputs",
		"name",
		"outputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderSchema := _ProviderSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderSchema)

	if err != nil {
		return err
	}

	*o = ProviderSchema(varProviderSchema)

	return err
}

type NullableProviderSchema struct {
	value *ProviderSchema
	isSet bool
}

func (v NullableProviderSchema) Get() *ProviderSchema {
	return v.value
}

func (v *NullableProviderSchema) Set(val *ProviderSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderSchema(val *ProviderSchema) *NullableProviderSchema {
	return &NullableProviderSchema{value: val, isSet: true}
}

func (v NullableProviderSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


