// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the UpdateEnvironmentRevisionTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvironmentRevisionTagRequest{}

// UpdateEnvironmentRevisionTagRequest Request to update an environment revision tag.
type UpdateEnvironmentRevisionTagRequest struct {
	// The revision number to associate with the tag.
	Revision *int64 `json:"revision,omitempty"`
}

// NewUpdateEnvironmentRevisionTagRequest instantiates a new UpdateEnvironmentRevisionTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentRevisionTagRequest() *UpdateEnvironmentRevisionTagRequest {
	this := UpdateEnvironmentRevisionTagRequest{}
	return &this
}

// NewUpdateEnvironmentRevisionTagRequestWithDefaults instantiates a new UpdateEnvironmentRevisionTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvironmentRevisionTagRequestWithDefaults() *UpdateEnvironmentRevisionTagRequest {
	this := UpdateEnvironmentRevisionTagRequest{}
	return &this
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *UpdateEnvironmentRevisionTagRequest) GetRevision() int64 {
	if o == nil || IsNil(o.Revision) {
		var ret int64
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentRevisionTagRequest) GetRevisionOk() (*int64, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *UpdateEnvironmentRevisionTagRequest) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given int64 and assigns it to the Revision field.
func (o *UpdateEnvironmentRevisionTagRequest) SetRevision(v int64) {
	o.Revision = &v
}

func (o UpdateEnvironmentRevisionTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvironmentRevisionTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	return toSerialize, nil
}

type NullableUpdateEnvironmentRevisionTagRequest struct {
	value *UpdateEnvironmentRevisionTagRequest
	isSet bool
}

func (v NullableUpdateEnvironmentRevisionTagRequest) Get() *UpdateEnvironmentRevisionTagRequest {
	return v.value
}

func (v *NullableUpdateEnvironmentRevisionTagRequest) Set(val *UpdateEnvironmentRevisionTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvironmentRevisionTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvironmentRevisionTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvironmentRevisionTagRequest(val *UpdateEnvironmentRevisionTagRequest) *NullableUpdateEnvironmentRevisionTagRequest {
	return &NullableUpdateEnvironmentRevisionTagRequest{value: val, isSet: true}
}

func (v NullableUpdateEnvironmentRevisionTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvironmentRevisionTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


