// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EscValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscValue{}

// EscValue A Value is the result of evaluating an expression within an environment definition.
type EscValue struct {
	// Secret is true if this value is secret.
	Secret *bool `json:"secret,omitempty"`
	Trace EscTrace `json:"trace"`
	// Unknown is true if this value is unknown.
	Unknown *bool `json:"unknown,omitempty"`
	// Value holds the concrete representation of the value. May be nil, bool, json.Number, string, []Value, or map[string]Value.
	Value interface{} `json:"value,omitempty"`
}

type _EscValue EscValue

// NewEscValue instantiates a new EscValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscValue(trace EscTrace) *EscValue {
	this := EscValue{}
	this.Trace = trace
	return &this
}

// NewEscValueWithDefaults instantiates a new EscValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscValueWithDefaults() *EscValue {
	this := EscValue{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *EscValue) GetSecret() bool {
	if o == nil || IsNil(o.Secret) {
		var ret bool
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscValue) GetSecretOk() (*bool, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *EscValue) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given bool and assigns it to the Secret field.
func (o *EscValue) SetSecret(v bool) {
	o.Secret = &v
}

// GetTrace returns the Trace field value
func (o *EscValue) GetTrace() EscTrace {
	if o == nil {
		var ret EscTrace
		return ret
	}

	return o.Trace
}

// GetTraceOk returns a tuple with the Trace field value
// and a boolean to check if the value has been set.
func (o *EscValue) GetTraceOk() (*EscTrace, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trace, true
}

// SetTrace sets field value
func (o *EscValue) SetTrace(v EscTrace) {
	o.Trace = v
}

// GetUnknown returns the Unknown field value if set, zero value otherwise.
func (o *EscValue) GetUnknown() bool {
	if o == nil || IsNil(o.Unknown) {
		var ret bool
		return ret
	}
	return *o.Unknown
}

// GetUnknownOk returns a tuple with the Unknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscValue) GetUnknownOk() (*bool, bool) {
	if o == nil || IsNil(o.Unknown) {
		return nil, false
	}
	return o.Unknown, true
}

// HasUnknown returns a boolean if a field has been set.
func (o *EscValue) HasUnknown() bool {
	if o != nil && !IsNil(o.Unknown) {
		return true
	}

	return false
}

// SetUnknown gets a reference to the given bool and assigns it to the Unknown field.
func (o *EscValue) SetUnknown(v bool) {
	o.Unknown = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EscValue) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EscValue) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *EscValue) HasValue() bool {
	if o != nil && IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *EscValue) SetValue(v interface{}) {
	o.Value = v
}

func (o EscValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	toSerialize["trace"] = o.Trace
	if !IsNil(o.Unknown) {
		toSerialize["unknown"] = o.Unknown
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *EscValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEscValue := _EscValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEscValue)

	if err != nil {
		return err
	}

	*o = EscValue(varEscValue)

	return err
}

type NullableEscValue struct {
	value *EscValue
	isSet bool
}

func (v NullableEscValue) Get() *EscValue {
	return v.value
}

func (v *NullableEscValue) Set(val *EscValue) {
	v.value = val
	v.isSet = true
}

func (v NullableEscValue) IsSet() bool {
	return v.isSet
}

func (v *NullableEscValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscValue(val *EscValue) *NullableEscValue {
	return &NullableEscValue{value: val, isSet: true}
}

func (v NullableEscValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


