// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"time"
)

// checks if the CreateEnvironmentScheduleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentScheduleRequest{}

// CreateEnvironmentScheduleRequest CreateEnvironmentScheduleRequest is an API request model to create all types of environment schedules.
type CreateEnvironmentScheduleRequest struct {
	// The schedule cron
	ScheduleCron *string `json:"scheduleCron,omitempty"`
	// The schedule once
	ScheduleOnce *time.Time `json:"scheduleOnce,omitempty"`
	SecretRotationRequest *CreateEnvironmentSecretRotationScheduleRequest `json:"secretRotationRequest,omitempty"`
}

// NewCreateEnvironmentScheduleRequest instantiates a new CreateEnvironmentScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentScheduleRequest() *CreateEnvironmentScheduleRequest {
	this := CreateEnvironmentScheduleRequest{}
	return &this
}

// NewCreateEnvironmentScheduleRequestWithDefaults instantiates a new CreateEnvironmentScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentScheduleRequestWithDefaults() *CreateEnvironmentScheduleRequest {
	this := CreateEnvironmentScheduleRequest{}
	return &this
}

// GetScheduleCron returns the ScheduleCron field value if set, zero value otherwise.
func (o *CreateEnvironmentScheduleRequest) GetScheduleCron() string {
	if o == nil || IsNil(o.ScheduleCron) {
		var ret string
		return ret
	}
	return *o.ScheduleCron
}

// GetScheduleCronOk returns a tuple with the ScheduleCron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentScheduleRequest) GetScheduleCronOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleCron) {
		return nil, false
	}
	return o.ScheduleCron, true
}

// HasScheduleCron returns a boolean if a field has been set.
func (o *CreateEnvironmentScheduleRequest) HasScheduleCron() bool {
	if o != nil && !IsNil(o.ScheduleCron) {
		return true
	}

	return false
}

// SetScheduleCron gets a reference to the given string and assigns it to the ScheduleCron field.
func (o *CreateEnvironmentScheduleRequest) SetScheduleCron(v string) {
	o.ScheduleCron = &v
}

// GetScheduleOnce returns the ScheduleOnce field value if set, zero value otherwise.
func (o *CreateEnvironmentScheduleRequest) GetScheduleOnce() time.Time {
	if o == nil || IsNil(o.ScheduleOnce) {
		var ret time.Time
		return ret
	}
	return *o.ScheduleOnce
}

// GetScheduleOnceOk returns a tuple with the ScheduleOnce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentScheduleRequest) GetScheduleOnceOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduleOnce) {
		return nil, false
	}
	return o.ScheduleOnce, true
}

// HasScheduleOnce returns a boolean if a field has been set.
func (o *CreateEnvironmentScheduleRequest) HasScheduleOnce() bool {
	if o != nil && !IsNil(o.ScheduleOnce) {
		return true
	}

	return false
}

// SetScheduleOnce gets a reference to the given time.Time and assigns it to the ScheduleOnce field.
func (o *CreateEnvironmentScheduleRequest) SetScheduleOnce(v time.Time) {
	o.ScheduleOnce = &v
}

// GetSecretRotationRequest returns the SecretRotationRequest field value if set, zero value otherwise.
func (o *CreateEnvironmentScheduleRequest) GetSecretRotationRequest() CreateEnvironmentSecretRotationScheduleRequest {
	if o == nil || IsNil(o.SecretRotationRequest) {
		var ret CreateEnvironmentSecretRotationScheduleRequest
		return ret
	}
	return *o.SecretRotationRequest
}

// GetSecretRotationRequestOk returns a tuple with the SecretRotationRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentScheduleRequest) GetSecretRotationRequestOk() (*CreateEnvironmentSecretRotationScheduleRequest, bool) {
	if o == nil || IsNil(o.SecretRotationRequest) {
		return nil, false
	}
	return o.SecretRotationRequest, true
}

// HasSecretRotationRequest returns a boolean if a field has been set.
func (o *CreateEnvironmentScheduleRequest) HasSecretRotationRequest() bool {
	if o != nil && !IsNil(o.SecretRotationRequest) {
		return true
	}

	return false
}

// SetSecretRotationRequest gets a reference to the given CreateEnvironmentSecretRotationScheduleRequest and assigns it to the SecretRotationRequest field.
func (o *CreateEnvironmentScheduleRequest) SetSecretRotationRequest(v CreateEnvironmentSecretRotationScheduleRequest) {
	o.SecretRotationRequest = &v
}

func (o CreateEnvironmentScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScheduleCron) {
		toSerialize["scheduleCron"] = o.ScheduleCron
	}
	if !IsNil(o.ScheduleOnce) {
		toSerialize["scheduleOnce"] = o.ScheduleOnce
	}
	if !IsNil(o.SecretRotationRequest) {
		toSerialize["secretRotationRequest"] = o.SecretRotationRequest
	}
	return toSerialize, nil
}

type NullableCreateEnvironmentScheduleRequest struct {
	value *CreateEnvironmentScheduleRequest
	isSet bool
}

func (v NullableCreateEnvironmentScheduleRequest) Get() *CreateEnvironmentScheduleRequest {
	return v.value
}

func (v *NullableCreateEnvironmentScheduleRequest) Set(val *CreateEnvironmentScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentScheduleRequest(val *CreateEnvironmentScheduleRequest) *NullableCreateEnvironmentScheduleRequest {
	return &NullableCreateEnvironmentScheduleRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


