// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ChangeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeRequest{}

// ChangeRequest struct for ChangeRequest
type ChangeRequest struct {
	// The change request ID
	Id string `json:"id"`
	// The current status of the change request
	Status string `json:"status"`
	// The organization ID
	OrgID string `json:"orgID"`
	CreatedBy UserInfo `json:"createdBy"`
	// The description/justification for this change request
	Description string `json:"description"`
	// When this change request was created
	CreatedAt time.Time `json:"createdAt"`
	Entity TargetEntity `json:"entity"`
	// The current revision number
	LatestRevisionNumber int64 `json:"latestRevisionNumber"`
}

type _ChangeRequest ChangeRequest

// NewChangeRequest instantiates a new ChangeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeRequest(id string, status string, orgID string, createdBy UserInfo, description string, createdAt time.Time, entity TargetEntity, latestRevisionNumber int64) *ChangeRequest {
	this := ChangeRequest{}
	this.Id = id
	this.Status = status
	this.OrgID = orgID
	this.CreatedBy = createdBy
	this.Description = description
	this.CreatedAt = createdAt
	this.Entity = entity
	this.LatestRevisionNumber = latestRevisionNumber
	return &this
}

// NewChangeRequestWithDefaults instantiates a new ChangeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeRequestWithDefaults() *ChangeRequest {
	this := ChangeRequest{}
	return &this
}

// GetId returns the Id field value
func (o *ChangeRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChangeRequest) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *ChangeRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ChangeRequest) SetStatus(v string) {
	o.Status = v
}

// GetOrgID returns the OrgID field value
func (o *ChangeRequest) GetOrgID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgID
}

// GetOrgIDOk returns a tuple with the OrgID field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetOrgIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgID, true
}

// SetOrgID sets field value
func (o *ChangeRequest) SetOrgID(v string) {
	o.OrgID = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ChangeRequest) GetCreatedBy() UserInfo {
	if o == nil {
		var ret UserInfo
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetCreatedByOk() (*UserInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ChangeRequest) SetCreatedBy(v UserInfo) {
	o.CreatedBy = v
}

// GetDescription returns the Description field value
func (o *ChangeRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ChangeRequest) SetDescription(v string) {
	o.Description = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ChangeRequest) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ChangeRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEntity returns the Entity field value
func (o *ChangeRequest) GetEntity() TargetEntity {
	if o == nil {
		var ret TargetEntity
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetEntityOk() (*TargetEntity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *ChangeRequest) SetEntity(v TargetEntity) {
	o.Entity = v
}

// GetLatestRevisionNumber returns the LatestRevisionNumber field value
func (o *ChangeRequest) GetLatestRevisionNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LatestRevisionNumber
}

// GetLatestRevisionNumberOk returns a tuple with the LatestRevisionNumber field value
// and a boolean to check if the value has been set.
func (o *ChangeRequest) GetLatestRevisionNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestRevisionNumber, true
}

// SetLatestRevisionNumber sets field value
func (o *ChangeRequest) SetLatestRevisionNumber(v int64) {
	o.LatestRevisionNumber = v
}

func (o ChangeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["orgID"] = o.OrgID
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["description"] = o.Description
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["entity"] = o.Entity
	toSerialize["latestRevisionNumber"] = o.LatestRevisionNumber
	return toSerialize, nil
}

func (o *ChangeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"orgID",
		"createdBy",
		"description",
		"createdAt",
		"entity",
		"latestRevisionNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeRequest := _ChangeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Allow unknown fields to be lenient with API responses that may include extra fields
	err = decoder.Decode(&varChangeRequest)

	if err != nil {
		return err
	}

	*o = ChangeRequest(varChangeRequest)

	return err
}

type NullableChangeRequest struct {
	value *ChangeRequest
	isSet bool
}

func (v NullableChangeRequest) Get() *ChangeRequest {
	return v.value
}

func (v *NullableChangeRequest) Set(val *ChangeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeRequest(val *ChangeRequest) *NullableChangeRequest {
	return &NullableChangeRequest{value: val, isSet: true}
}

func (v NullableChangeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


