// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListEnvironmentSecretRotationHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEnvironmentSecretRotationHistoryResponse{}

// ListEnvironmentSecretRotationHistoryResponse Response containing a list of secret rotation history events for an environment.
type ListEnvironmentSecretRotationHistoryResponse struct {
	// The list of secret rotation events
	Events []SecretRotationEvent `json:"events"`
}

type _ListEnvironmentSecretRotationHistoryResponse ListEnvironmentSecretRotationHistoryResponse

// NewListEnvironmentSecretRotationHistoryResponse instantiates a new ListEnvironmentSecretRotationHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEnvironmentSecretRotationHistoryResponse(events []SecretRotationEvent) *ListEnvironmentSecretRotationHistoryResponse {
	this := ListEnvironmentSecretRotationHistoryResponse{}
	this.Events = events
	return &this
}

// NewListEnvironmentSecretRotationHistoryResponseWithDefaults instantiates a new ListEnvironmentSecretRotationHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEnvironmentSecretRotationHistoryResponseWithDefaults() *ListEnvironmentSecretRotationHistoryResponse {
	this := ListEnvironmentSecretRotationHistoryResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *ListEnvironmentSecretRotationHistoryResponse) GetEvents() []SecretRotationEvent {
	if o == nil {
		var ret []SecretRotationEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentSecretRotationHistoryResponse) GetEventsOk() ([]SecretRotationEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *ListEnvironmentSecretRotationHistoryResponse) SetEvents(v []SecretRotationEvent) {
	o.Events = v
}

func (o ListEnvironmentSecretRotationHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEnvironmentSecretRotationHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *ListEnvironmentSecretRotationHistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEnvironmentSecretRotationHistoryResponse := _ListEnvironmentSecretRotationHistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListEnvironmentSecretRotationHistoryResponse)

	if err != nil {
		return err
	}

	*o = ListEnvironmentSecretRotationHistoryResponse(varListEnvironmentSecretRotationHistoryResponse)

	return err
}

type NullableListEnvironmentSecretRotationHistoryResponse struct {
	value *ListEnvironmentSecretRotationHistoryResponse
	isSet bool
}

func (v NullableListEnvironmentSecretRotationHistoryResponse) Get() *ListEnvironmentSecretRotationHistoryResponse {
	return v.value
}

func (v *NullableListEnvironmentSecretRotationHistoryResponse) Set(val *ListEnvironmentSecretRotationHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListEnvironmentSecretRotationHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListEnvironmentSecretRotationHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEnvironmentSecretRotationHistoryResponse(val *ListEnvironmentSecretRotationHistoryResponse) *NullableListEnvironmentSecretRotationHistoryResponse {
	return &NullableListEnvironmentSecretRotationHistoryResponse{value: val, isSet: true}
}

func (v NullableListEnvironmentSecretRotationHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEnvironmentSecretRotationHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


