// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the SubmitChangeRequestInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitChangeRequestInfo{}

// SubmitChangeRequestInfo struct for SubmitChangeRequestInfo
type SubmitChangeRequestInfo struct {
	Description *string `json:"description,omitempty"`
}

// NewSubmitChangeRequestInfo instantiates a new SubmitChangeRequestInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitChangeRequestInfo() *SubmitChangeRequestInfo {
	this := SubmitChangeRequestInfo{}
	return &this
}

// NewSubmitChangeRequestInfoWithDefaults instantiates a new SubmitChangeRequestInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitChangeRequestInfoWithDefaults() *SubmitChangeRequestInfo {
	this := SubmitChangeRequestInfo{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SubmitChangeRequestInfo) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitChangeRequestInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SubmitChangeRequestInfo) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SubmitChangeRequestInfo) SetDescription(v string) {
	o.Description = &v
}

func (o SubmitChangeRequestInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitChangeRequestInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableSubmitChangeRequestInfo struct {
	value *SubmitChangeRequestInfo
	isSet bool
}

func (v NullableSubmitChangeRequestInfo) Get() *SubmitChangeRequestInfo {
	return v.value
}

func (v *NullableSubmitChangeRequestInfo) Set(val *SubmitChangeRequestInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitChangeRequestInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitChangeRequestInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitChangeRequestInfo(val *SubmitChangeRequestInfo) *NullableSubmitChangeRequestInfo {
	return &NullableSubmitChangeRequestInfo{value: val, isSet: true}
}

func (v NullableSubmitChangeRequestInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitChangeRequestInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


