// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the ListChangeRequestsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListChangeRequestsResponse{}

// ListChangeRequestsResponse struct for ListChangeRequestsResponse
type ListChangeRequestsResponse struct {
	// The list of change requests
	ChangeRequests []ChangeRequest `json:"changeRequests,omitempty"`
	// Continuation token for pagination
	NextToken *string `json:"nextToken,omitempty"`
}

// NewListChangeRequestsResponse instantiates a new ListChangeRequestsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListChangeRequestsResponse() *ListChangeRequestsResponse {
	this := ListChangeRequestsResponse{}
	return &this
}

// NewListChangeRequestsResponseWithDefaults instantiates a new ListChangeRequestsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListChangeRequestsResponseWithDefaults() *ListChangeRequestsResponse {
	this := ListChangeRequestsResponse{}
	return &this
}

// GetChangeRequests returns the ChangeRequests field value if set, zero value otherwise.
func (o *ListChangeRequestsResponse) GetChangeRequests() []ChangeRequest {
	if o == nil || IsNil(o.ChangeRequests) {
		var ret []ChangeRequest
		return ret
	}
	return o.ChangeRequests
}

// GetChangeRequestsOk returns a tuple with the ChangeRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListChangeRequestsResponse) GetChangeRequestsOk() ([]ChangeRequest, bool) {
	if o == nil || IsNil(o.ChangeRequests) {
		return nil, false
	}
	return o.ChangeRequests, true
}

// HasChangeRequests returns a boolean if a field has been set.
func (o *ListChangeRequestsResponse) HasChangeRequests() bool {
	if o != nil && !IsNil(o.ChangeRequests) {
		return true
	}

	return false
}

// SetChangeRequests gets a reference to the given []ChangeRequest and assigns it to the ChangeRequests field.
func (o *ListChangeRequestsResponse) SetChangeRequests(v []ChangeRequest) {
	o.ChangeRequests = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListChangeRequestsResponse) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListChangeRequestsResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListChangeRequestsResponse) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListChangeRequestsResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListChangeRequestsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListChangeRequestsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChangeRequests) {
		toSerialize["changeRequests"] = o.ChangeRequests
	}
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableListChangeRequestsResponse struct {
	value *ListChangeRequestsResponse
	isSet bool
}

func (v NullableListChangeRequestsResponse) Get() *ListChangeRequestsResponse {
	return v.value
}

func (v *NullableListChangeRequestsResponse) Set(val *ListChangeRequestsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListChangeRequestsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListChangeRequestsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListChangeRequestsResponse(val *ListChangeRequestsResponse) *NullableListChangeRequestsResponse {
	return &NullableListChangeRequestsResponse{value: val, isSet: true}
}

func (v NullableListChangeRequestsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListChangeRequestsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


