// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentMetadata{}

// EnvironmentMetadata EnvironmentMetadata contains read-only metadata about a Pulumi environment.
type EnvironmentMetadata struct {
	ActiveChangeRequest *ChangeRequestRef `json:"activeChangeRequest,omitempty"`
	// GatedActions indicates which actions on this environment require change request approval.
	GatedActions []string `json:"gatedActions,omitempty"`
	// Environment metadata follows other Pulumi Cloud \"Metadata\" fields and contains read-only information about the environment
	Id string `json:"id"`
	// OpenRequestNeeded indicates whether an open request is currently needed in order to open the environment.
	OpenRequestNeeded *bool `json:"openRequestNeeded,omitempty"`
}

type _EnvironmentMetadata EnvironmentMetadata

// NewEnvironmentMetadata instantiates a new EnvironmentMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentMetadata(id string) *EnvironmentMetadata {
	this := EnvironmentMetadata{}
	this.Id = id
	return &this
}

// NewEnvironmentMetadataWithDefaults instantiates a new EnvironmentMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentMetadataWithDefaults() *EnvironmentMetadata {
	this := EnvironmentMetadata{}
	return &this
}

// GetActiveChangeRequest returns the ActiveChangeRequest field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetActiveChangeRequest() ChangeRequestRef {
	if o == nil || IsNil(o.ActiveChangeRequest) {
		var ret ChangeRequestRef
		return ret
	}
	return *o.ActiveChangeRequest
}

// GetActiveChangeRequestOk returns a tuple with the ActiveChangeRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetActiveChangeRequestOk() (*ChangeRequestRef, bool) {
	if o == nil || IsNil(o.ActiveChangeRequest) {
		return nil, false
	}
	return o.ActiveChangeRequest, true
}

// HasActiveChangeRequest returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasActiveChangeRequest() bool {
	if o != nil && !IsNil(o.ActiveChangeRequest) {
		return true
	}

	return false
}

// SetActiveChangeRequest gets a reference to the given ChangeRequestRef and assigns it to the ActiveChangeRequest field.
func (o *EnvironmentMetadata) SetActiveChangeRequest(v ChangeRequestRef) {
	o.ActiveChangeRequest = &v
}

// GetGatedActions returns the GatedActions field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetGatedActions() []string {
	if o == nil || IsNil(o.GatedActions) {
		var ret []string
		return ret
	}
	return o.GatedActions
}

// GetGatedActionsOk returns a tuple with the GatedActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetGatedActionsOk() ([]string, bool) {
	if o == nil || IsNil(o.GatedActions) {
		return nil, false
	}
	return o.GatedActions, true
}

// HasGatedActions returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasGatedActions() bool {
	if o != nil && !IsNil(o.GatedActions) {
		return true
	}

	return false
}

// SetGatedActions gets a reference to the given []string and assigns it to the GatedActions field.
func (o *EnvironmentMetadata) SetGatedActions(v []string) {
	o.GatedActions = v
}

// GetId returns the Id field value
func (o *EnvironmentMetadata) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnvironmentMetadata) SetId(v string) {
	o.Id = v
}

// GetOpenRequestNeeded returns the OpenRequestNeeded field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetOpenRequestNeeded() bool {
	if o == nil || IsNil(o.OpenRequestNeeded) {
		var ret bool
		return ret
	}
	return *o.OpenRequestNeeded
}

// GetOpenRequestNeededOk returns a tuple with the OpenRequestNeeded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetOpenRequestNeededOk() (*bool, bool) {
	if o == nil || IsNil(o.OpenRequestNeeded) {
		return nil, false
	}
	return o.OpenRequestNeeded, true
}

// HasOpenRequestNeeded returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasOpenRequestNeeded() bool {
	if o != nil && !IsNil(o.OpenRequestNeeded) {
		return true
	}

	return false
}

// SetOpenRequestNeeded gets a reference to the given bool and assigns it to the OpenRequestNeeded field.
func (o *EnvironmentMetadata) SetOpenRequestNeeded(v bool) {
	o.OpenRequestNeeded = &v
}

func (o EnvironmentMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActiveChangeRequest) {
		toSerialize["activeChangeRequest"] = o.ActiveChangeRequest
	}
	if !IsNil(o.GatedActions) {
		toSerialize["gatedActions"] = o.GatedActions
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.OpenRequestNeeded) {
		toSerialize["openRequestNeeded"] = o.OpenRequestNeeded
	}
	return toSerialize, nil
}

func (o *EnvironmentMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentMetadata := _EnvironmentMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentMetadata)

	if err != nil {
		return err
	}

	*o = EnvironmentMetadata(varEnvironmentMetadata)

	return err
}

type NullableEnvironmentMetadata struct {
	value *EnvironmentMetadata
	isSet bool
}

func (v NullableEnvironmentMetadata) Get() *EnvironmentMetadata {
	return v.value
}

func (v *NullableEnvironmentMetadata) Set(val *EnvironmentMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentMetadata(val *EnvironmentMetadata) *NullableEnvironmentMetadata {
	return &NullableEnvironmentMetadata{value: val, isSet: true}
}

func (v NullableEnvironmentMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


