// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SecretRotationEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretRotationEvent{}

// SecretRotationEvent An event representing a secret rotation operation on an environment.
type SecretRotationEvent struct {
	// The timestamp when the rotation completed.
	Completed *time.Time `json:"completed,omitempty"`
	// The timestamp when this rotation event was created.
	Created time.Time `json:"created"`
	// The ID of the environment being rotated.
	EnvironmentId string `json:"environmentId"`
	// An error message if the rotation failed.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// The unique identifier for this rotation event.
	Id string `json:"id"`
	// The environment revision after the rotation, if completed.
	PostRotationRevision *int64 `json:"postRotationRevision,omitempty"`
	// The environment revision before the rotation.
	PreRotationRevision int64 `json:"preRotationRevision"`
	// The individual secret rotations within this event.
	Rotations []SecretRotation `json:"rotations"`
	// The ID of the scheduled action that triggered this rotation, if any.
	ScheduledActionID *string `json:"scheduledActionID,omitempty"`
	// The current status of the rotation event.
	Status string `json:"status"`
	// The ID of the user who initiated the rotation.
	UserID string `json:"userID"`
}

type _SecretRotationEvent SecretRotationEvent

// NewSecretRotationEvent instantiates a new SecretRotationEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretRotationEvent(created time.Time, environmentId string, id string, preRotationRevision int64, rotations []SecretRotation, status string, userID string) *SecretRotationEvent {
	this := SecretRotationEvent{}
	this.Created = created
	this.EnvironmentId = environmentId
	this.Id = id
	this.PreRotationRevision = preRotationRevision
	this.Rotations = rotations
	this.Status = status
	this.UserID = userID
	return &this
}

// NewSecretRotationEventWithDefaults instantiates a new SecretRotationEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretRotationEventWithDefaults() *SecretRotationEvent {
	this := SecretRotationEvent{}
	return &this
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *SecretRotationEvent) GetCompleted() time.Time {
	if o == nil || IsNil(o.Completed) {
		var ret time.Time
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetCompletedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *SecretRotationEvent) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given time.Time and assigns it to the Completed field.
func (o *SecretRotationEvent) SetCompleted(v time.Time) {
	o.Completed = &v
}

// GetCreated returns the Created field value
func (o *SecretRotationEvent) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *SecretRotationEvent) SetCreated(v time.Time) {
	o.Created = v
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *SecretRotationEvent) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *SecretRotationEvent) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *SecretRotationEvent) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *SecretRotationEvent) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *SecretRotationEvent) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetId returns the Id field value
func (o *SecretRotationEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretRotationEvent) SetId(v string) {
	o.Id = v
}

// GetPostRotationRevision returns the PostRotationRevision field value if set, zero value otherwise.
func (o *SecretRotationEvent) GetPostRotationRevision() int64 {
	if o == nil || IsNil(o.PostRotationRevision) {
		var ret int64
		return ret
	}
	return *o.PostRotationRevision
}

// GetPostRotationRevisionOk returns a tuple with the PostRotationRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetPostRotationRevisionOk() (*int64, bool) {
	if o == nil || IsNil(o.PostRotationRevision) {
		return nil, false
	}
	return o.PostRotationRevision, true
}

// HasPostRotationRevision returns a boolean if a field has been set.
func (o *SecretRotationEvent) HasPostRotationRevision() bool {
	if o != nil && !IsNil(o.PostRotationRevision) {
		return true
	}

	return false
}

// SetPostRotationRevision gets a reference to the given int64 and assigns it to the PostRotationRevision field.
func (o *SecretRotationEvent) SetPostRotationRevision(v int64) {
	o.PostRotationRevision = &v
}

// GetPreRotationRevision returns the PreRotationRevision field value
func (o *SecretRotationEvent) GetPreRotationRevision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PreRotationRevision
}

// GetPreRotationRevisionOk returns a tuple with the PreRotationRevision field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetPreRotationRevisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreRotationRevision, true
}

// SetPreRotationRevision sets field value
func (o *SecretRotationEvent) SetPreRotationRevision(v int64) {
	o.PreRotationRevision = v
}

// GetRotations returns the Rotations field value
func (o *SecretRotationEvent) GetRotations() []SecretRotation {
	if o == nil {
		var ret []SecretRotation
		return ret
	}

	return o.Rotations
}

// GetRotationsOk returns a tuple with the Rotations field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetRotationsOk() ([]SecretRotation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rotations, true
}

// SetRotations sets field value
func (o *SecretRotationEvent) SetRotations(v []SecretRotation) {
	o.Rotations = v
}

// GetScheduledActionID returns the ScheduledActionID field value if set, zero value otherwise.
func (o *SecretRotationEvent) GetScheduledActionID() string {
	if o == nil || IsNil(o.ScheduledActionID) {
		var ret string
		return ret
	}
	return *o.ScheduledActionID
}

// GetScheduledActionIDOk returns a tuple with the ScheduledActionID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetScheduledActionIDOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledActionID) {
		return nil, false
	}
	return o.ScheduledActionID, true
}

// HasScheduledActionID returns a boolean if a field has been set.
func (o *SecretRotationEvent) HasScheduledActionID() bool {
	if o != nil && !IsNil(o.ScheduledActionID) {
		return true
	}

	return false
}

// SetScheduledActionID gets a reference to the given string and assigns it to the ScheduledActionID field.
func (o *SecretRotationEvent) SetScheduledActionID(v string) {
	o.ScheduledActionID = &v
}

// GetStatus returns the Status field value
func (o *SecretRotationEvent) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecretRotationEvent) SetStatus(v string) {
	o.Status = v
}

// GetUserID returns the UserID field value
func (o *SecretRotationEvent) GetUserID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *SecretRotationEvent) GetUserIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *SecretRotationEvent) SetUserID(v string) {
	o.UserID = v
}

func (o SecretRotationEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretRotationEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	toSerialize["created"] = o.Created
	toSerialize["environmentId"] = o.EnvironmentId
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.PostRotationRevision) {
		toSerialize["postRotationRevision"] = o.PostRotationRevision
	}
	toSerialize["preRotationRevision"] = o.PreRotationRevision
	toSerialize["rotations"] = o.Rotations
	if !IsNil(o.ScheduledActionID) {
		toSerialize["scheduledActionID"] = o.ScheduledActionID
	}
	toSerialize["status"] = o.Status
	toSerialize["userID"] = o.UserID
	return toSerialize, nil
}

func (o *SecretRotationEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"environmentId",
		"id",
		"preRotationRevision",
		"rotations",
		"status",
		"userID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretRotationEvent := _SecretRotationEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretRotationEvent)

	if err != nil {
		return err
	}

	*o = SecretRotationEvent(varSecretRotationEvent)

	return err
}

type NullableSecretRotationEvent struct {
	value *SecretRotationEvent
	isSet bool
}

func (v NullableSecretRotationEvent) Get() *SecretRotationEvent {
	return v.value
}

func (v *NullableSecretRotationEvent) Set(val *SecretRotationEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretRotationEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretRotationEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretRotationEvent(val *SecretRotationEvent) *NullableSecretRotationEvent {
	return &NullableSecretRotationEvent{value: val, isSet: true}
}

func (v NullableSecretRotationEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretRotationEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


