// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the EnvironmentDiagnostic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentDiagnostic{}

// EnvironmentDiagnostic EnvironmentDiagnostic represents a diagnostic message associated with an environment definition.
type EnvironmentDiagnostic struct {
	// The path within the environment definition where the diagnostic occurred.
	Path *string `json:"path,omitempty"`
	Range *EscRange `json:"range,omitempty"`
	// A summary of the diagnostic message.
	Summary *string `json:"summary,omitempty"`
}

// NewEnvironmentDiagnostic instantiates a new EnvironmentDiagnostic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentDiagnostic() *EnvironmentDiagnostic {
	this := EnvironmentDiagnostic{}
	return &this
}

// NewEnvironmentDiagnosticWithDefaults instantiates a new EnvironmentDiagnostic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentDiagnosticWithDefaults() *EnvironmentDiagnostic {
	this := EnvironmentDiagnostic{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *EnvironmentDiagnostic) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDiagnostic) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *EnvironmentDiagnostic) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *EnvironmentDiagnostic) SetPath(v string) {
	o.Path = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *EnvironmentDiagnostic) GetRange() EscRange {
	if o == nil || IsNil(o.Range) {
		var ret EscRange
		return ret
	}
	return *o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDiagnostic) GetRangeOk() (*EscRange, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *EnvironmentDiagnostic) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given EscRange and assigns it to the Range field.
func (o *EnvironmentDiagnostic) SetRange(v EscRange) {
	o.Range = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *EnvironmentDiagnostic) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDiagnostic) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *EnvironmentDiagnostic) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *EnvironmentDiagnostic) SetSummary(v string) {
	o.Summary = &v
}

func (o EnvironmentDiagnostic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentDiagnostic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableEnvironmentDiagnostic struct {
	value *EnvironmentDiagnostic
	isSet bool
}

func (v NullableEnvironmentDiagnostic) Get() *EnvironmentDiagnostic {
	return v.value
}

func (v *NullableEnvironmentDiagnostic) Set(val *EnvironmentDiagnostic) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentDiagnostic) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentDiagnostic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentDiagnostic(val *EnvironmentDiagnostic) *NullableEnvironmentDiagnostic {
	return &NullableEnvironmentDiagnostic{value: val, isSet: true}
}

func (v NullableEnvironmentDiagnostic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentDiagnostic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


