// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListEnvironmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEnvironmentsResponse{}

// ListEnvironmentsResponse Response containing a list of environments for an organization.
type ListEnvironmentsResponse struct {
	// The list of environments
	Environments []OrgEnvironment `json:"environments"`
	// Token for fetching the next page of results
	NextToken *string `json:"nextToken,omitempty"`
}

type _ListEnvironmentsResponse ListEnvironmentsResponse

// NewListEnvironmentsResponse instantiates a new ListEnvironmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEnvironmentsResponse(environments []OrgEnvironment) *ListEnvironmentsResponse {
	this := ListEnvironmentsResponse{}
	this.Environments = environments
	return &this
}

// NewListEnvironmentsResponseWithDefaults instantiates a new ListEnvironmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEnvironmentsResponseWithDefaults() *ListEnvironmentsResponse {
	this := ListEnvironmentsResponse{}
	return &this
}

// GetEnvironments returns the Environments field value
func (o *ListEnvironmentsResponse) GetEnvironments() []OrgEnvironment {
	if o == nil {
		var ret []OrgEnvironment
		return ret
	}

	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentsResponse) GetEnvironmentsOk() ([]OrgEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environments, true
}

// SetEnvironments sets field value
func (o *ListEnvironmentsResponse) SetEnvironments(v []OrgEnvironment) {
	o.Environments = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListEnvironmentsResponse) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEnvironmentsResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListEnvironmentsResponse) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListEnvironmentsResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListEnvironmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEnvironmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environments"] = o.Environments
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	return toSerialize, nil
}

func (o *ListEnvironmentsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEnvironmentsResponse := _ListEnvironmentsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListEnvironmentsResponse)

	if err != nil {
		return err
	}

	*o = ListEnvironmentsResponse(varListEnvironmentsResponse)

	return err
}

type NullableListEnvironmentsResponse struct {
	value *ListEnvironmentsResponse
	isSet bool
}

func (v NullableListEnvironmentsResponse) Get() *ListEnvironmentsResponse {
	return v.value
}

func (v *NullableListEnvironmentsResponse) Set(val *ListEnvironmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListEnvironmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListEnvironmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEnvironmentsResponse(val *ListEnvironmentsResponse) *NullableListEnvironmentsResponse {
	return &NullableListEnvironmentsResponse{value: val, isSet: true}
}

func (v NullableListEnvironmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEnvironmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


