// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the EscEnvironment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscEnvironment{}

// EscEnvironment An Environment contains the result of evaluating an environment definition.
type EscEnvironment struct {
	ExecutionContext *EscEvaluatedExecutionContext `json:"executionContext,omitempty"`
	// Exprs contains the AST for each expression in the environment definition.
	Exprs *map[string]EscExpr `json:"exprs,omitempty"`
	// Properties contains the detailed values produced by the environment.
	Properties *map[string]EscValue `json:"properties,omitempty"`
	// Schema contains the schema for Properties.
	Schema interface{} `json:"schema,omitempty"`
}

// NewEscEnvironment instantiates a new EscEnvironment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscEnvironment() *EscEnvironment {
	this := EscEnvironment{}
	return &this
}

// NewEscEnvironmentWithDefaults instantiates a new EscEnvironment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscEnvironmentWithDefaults() *EscEnvironment {
	this := EscEnvironment{}
	return &this
}

// GetExecutionContext returns the ExecutionContext field value if set, zero value otherwise.
func (o *EscEnvironment) GetExecutionContext() EscEvaluatedExecutionContext {
	if o == nil || IsNil(o.ExecutionContext) {
		var ret EscEvaluatedExecutionContext
		return ret
	}
	return *o.ExecutionContext
}

// GetExecutionContextOk returns a tuple with the ExecutionContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscEnvironment) GetExecutionContextOk() (*EscEvaluatedExecutionContext, bool) {
	if o == nil || IsNil(o.ExecutionContext) {
		return nil, false
	}
	return o.ExecutionContext, true
}

// HasExecutionContext returns a boolean if a field has been set.
func (o *EscEnvironment) HasExecutionContext() bool {
	if o != nil && !IsNil(o.ExecutionContext) {
		return true
	}

	return false
}

// SetExecutionContext gets a reference to the given EscEvaluatedExecutionContext and assigns it to the ExecutionContext field.
func (o *EscEnvironment) SetExecutionContext(v EscEvaluatedExecutionContext) {
	o.ExecutionContext = &v
}

// GetExprs returns the Exprs field value if set, zero value otherwise.
func (o *EscEnvironment) GetExprs() map[string]EscExpr {
	if o == nil || IsNil(o.Exprs) {
		var ret map[string]EscExpr
		return ret
	}
	return *o.Exprs
}

// GetExprsOk returns a tuple with the Exprs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscEnvironment) GetExprsOk() (*map[string]EscExpr, bool) {
	if o == nil || IsNil(o.Exprs) {
		return nil, false
	}
	return o.Exprs, true
}

// HasExprs returns a boolean if a field has been set.
func (o *EscEnvironment) HasExprs() bool {
	if o != nil && !IsNil(o.Exprs) {
		return true
	}

	return false
}

// SetExprs gets a reference to the given map[string]EscExpr and assigns it to the Exprs field.
func (o *EscEnvironment) SetExprs(v map[string]EscExpr) {
	o.Exprs = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *EscEnvironment) GetProperties() map[string]EscValue {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]EscValue
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscEnvironment) GetPropertiesOk() (*map[string]EscValue, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *EscEnvironment) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]EscValue and assigns it to the Properties field.
func (o *EscEnvironment) SetProperties(v map[string]EscValue) {
	o.Properties = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EscEnvironment) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EscEnvironment) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *EscEnvironment) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *EscEnvironment) SetSchema(v interface{}) {
	o.Schema = v
}

func (o EscEnvironment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscEnvironment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExecutionContext) {
		toSerialize["executionContext"] = o.ExecutionContext
	}
	if !IsNil(o.Exprs) {
		toSerialize["exprs"] = o.Exprs
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableEscEnvironment struct {
	value *EscEnvironment
	isSet bool
}

func (v NullableEscEnvironment) Get() *EscEnvironment {
	return v.value
}

func (v *NullableEscEnvironment) Set(val *EscEnvironment) {
	v.value = val
	v.isSet = true
}

func (v NullableEscEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableEscEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscEnvironment(val *EscEnvironment) *NullableEscEnvironment {
	return &NullableEscEnvironment{value: val, isSet: true}
}

func (v NullableEscEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


