// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiateOAuthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateOAuthResponse{}

// InitiateOAuthResponse Response from OAuth initiation containing authorization URL and session details
type InitiateOAuthResponse struct {
	// Session identifier for tracking the OAuth flow
	SessionID string `json:"sessionID"`
	// Authorization URL to redirect user to
	Url string `json:"url"`
}

type _InitiateOAuthResponse InitiateOAuthResponse

// NewInitiateOAuthResponse instantiates a new InitiateOAuthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateOAuthResponse(sessionID string, url string) *InitiateOAuthResponse {
	this := InitiateOAuthResponse{}
	this.SessionID = sessionID
	this.Url = url
	return &this
}

// NewInitiateOAuthResponseWithDefaults instantiates a new InitiateOAuthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateOAuthResponseWithDefaults() *InitiateOAuthResponse {
	this := InitiateOAuthResponse{}
	return &this
}

// GetSessionID returns the SessionID field value
func (o *InitiateOAuthResponse) GetSessionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value
// and a boolean to check if the value has been set.
func (o *InitiateOAuthResponse) GetSessionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionID, true
}

// SetSessionID sets field value
func (o *InitiateOAuthResponse) SetSessionID(v string) {
	o.SessionID = v
}

// GetUrl returns the Url field value
func (o *InitiateOAuthResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *InitiateOAuthResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *InitiateOAuthResponse) SetUrl(v string) {
	o.Url = v
}

func (o InitiateOAuthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateOAuthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionID"] = o.SessionID
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *InitiateOAuthResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionID",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateOAuthResponse := _InitiateOAuthResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiateOAuthResponse)

	if err != nil {
		return err
	}

	*o = InitiateOAuthResponse(varInitiateOAuthResponse)

	return err
}

type NullableInitiateOAuthResponse struct {
	value *InitiateOAuthResponse
	isSet bool
}

func (v NullableInitiateOAuthResponse) Get() *InitiateOAuthResponse {
	return v.value
}

func (v *NullableInitiateOAuthResponse) Set(val *InitiateOAuthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateOAuthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateOAuthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateOAuthResponse(val *InitiateOAuthResponse) *NullableInitiateOAuthResponse {
	return &NullableInitiateOAuthResponse{value: val, isSet: true}
}

func (v NullableInitiateOAuthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateOAuthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


