// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DecryptEnvironmentSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecryptEnvironmentSecretsResponse{}

// DecryptEnvironmentSecretsResponse DecryptEnvironmentSecretsResponse defines the response body for multiple decrypted values.
type DecryptEnvironmentSecretsResponse struct {
	// The list of decrypted plaintext values.
	Plaintexts []string `json:"plaintexts"`
}

type _DecryptEnvironmentSecretsResponse DecryptEnvironmentSecretsResponse

// NewDecryptEnvironmentSecretsResponse instantiates a new DecryptEnvironmentSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecryptEnvironmentSecretsResponse(plaintexts []string) *DecryptEnvironmentSecretsResponse {
	this := DecryptEnvironmentSecretsResponse{}
	this.Plaintexts = plaintexts
	return &this
}

// NewDecryptEnvironmentSecretsResponseWithDefaults instantiates a new DecryptEnvironmentSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecryptEnvironmentSecretsResponseWithDefaults() *DecryptEnvironmentSecretsResponse {
	this := DecryptEnvironmentSecretsResponse{}
	return &this
}

// GetPlaintexts returns the Plaintexts field value
func (o *DecryptEnvironmentSecretsResponse) GetPlaintexts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Plaintexts
}

// GetPlaintextsOk returns a tuple with the Plaintexts field value
// and a boolean to check if the value has been set.
func (o *DecryptEnvironmentSecretsResponse) GetPlaintextsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plaintexts, true
}

// SetPlaintexts sets field value
func (o *DecryptEnvironmentSecretsResponse) SetPlaintexts(v []string) {
	o.Plaintexts = v
}

func (o DecryptEnvironmentSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecryptEnvironmentSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plaintexts"] = o.Plaintexts
	return toSerialize, nil
}

func (o *DecryptEnvironmentSecretsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plaintexts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecryptEnvironmentSecretsResponse := _DecryptEnvironmentSecretsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDecryptEnvironmentSecretsResponse)

	if err != nil {
		return err
	}

	*o = DecryptEnvironmentSecretsResponse(varDecryptEnvironmentSecretsResponse)

	return err
}

type NullableDecryptEnvironmentSecretsResponse struct {
	value *DecryptEnvironmentSecretsResponse
	isSet bool
}

func (v NullableDecryptEnvironmentSecretsResponse) Get() *DecryptEnvironmentSecretsResponse {
	return v.value
}

func (v *NullableDecryptEnvironmentSecretsResponse) Set(val *DecryptEnvironmentSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDecryptEnvironmentSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDecryptEnvironmentSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecryptEnvironmentSecretsResponse(val *DecryptEnvironmentSecretsResponse) *NullableDecryptEnvironmentSecretsResponse {
	return &NullableDecryptEnvironmentSecretsResponse{value: val, isSet: true}
}

func (v NullableDecryptEnvironmentSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecryptEnvironmentSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


