// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EscTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscTrace{}

// EscTrace Trace holds information about the expression and base of a value.
type EscTrace struct {
	Base *EscValue `json:"base,omitempty"`
	Def EscRange `json:"def"`
}

type _EscTrace EscTrace

// NewEscTrace instantiates a new EscTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscTrace(def EscRange) *EscTrace {
	this := EscTrace{}
	this.Def = def
	return &this
}

// NewEscTraceWithDefaults instantiates a new EscTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscTraceWithDefaults() *EscTrace {
	this := EscTrace{}
	return &this
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *EscTrace) GetBase() EscValue {
	if o == nil || IsNil(o.Base) {
		var ret EscValue
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscTrace) GetBaseOk() (*EscValue, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *EscTrace) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given EscValue and assigns it to the Base field.
func (o *EscTrace) SetBase(v EscValue) {
	o.Base = &v
}

// GetDef returns the Def field value
func (o *EscTrace) GetDef() EscRange {
	if o == nil {
		var ret EscRange
		return ret
	}

	return o.Def
}

// GetDefOk returns a tuple with the Def field value
// and a boolean to check if the value has been set.
func (o *EscTrace) GetDefOk() (*EscRange, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Def, true
}

// SetDef sets field value
func (o *EscTrace) SetDef(v EscRange) {
	o.Def = v
}

func (o EscTrace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	toSerialize["def"] = o.Def
	return toSerialize, nil
}

func (o *EscTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"def",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEscTrace := _EscTrace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEscTrace)

	if err != nil {
		return err
	}

	*o = EscTrace(varEscTrace)

	return err
}

type NullableEscTrace struct {
	value *EscTrace
	isSet bool
}

func (v NullableEscTrace) Get() *EscTrace {
	return v.value
}

func (v *NullableEscTrace) Set(val *EscTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableEscTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableEscTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscTrace(val *EscTrace) *NullableEscTrace {
	return &NullableEscTrace{value: val, isSet: true}
}

func (v NullableEscTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


