// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiateOAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateOAuthRequest{}

// InitiateOAuthRequest Request to initiate OAuth flow for cloud provider authentication
type InitiateOAuthRequest struct {
	Provider CloudSetupProvider `json:"provider"`
}

type _InitiateOAuthRequest InitiateOAuthRequest

// NewInitiateOAuthRequest instantiates a new InitiateOAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateOAuthRequest(provider CloudSetupProvider) *InitiateOAuthRequest {
	this := InitiateOAuthRequest{}
	this.Provider = provider
	return &this
}

// NewInitiateOAuthRequestWithDefaults instantiates a new InitiateOAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateOAuthRequestWithDefaults() *InitiateOAuthRequest {
	this := InitiateOAuthRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *InitiateOAuthRequest) GetProvider() CloudSetupProvider {
	if o == nil {
		var ret CloudSetupProvider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *InitiateOAuthRequest) GetProviderOk() (*CloudSetupProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *InitiateOAuthRequest) SetProvider(v CloudSetupProvider) {
	o.Provider = v
}

func (o InitiateOAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateOAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *InitiateOAuthRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateOAuthRequest := _InitiateOAuthRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiateOAuthRequest)

	if err != nil {
		return err
	}

	*o = InitiateOAuthRequest(varInitiateOAuthRequest)

	return err
}

type NullableInitiateOAuthRequest struct {
	value *InitiateOAuthRequest
	isSet bool
}

func (v NullableInitiateOAuthRequest) Get() *InitiateOAuthRequest {
	return v.value
}

func (v *NullableInitiateOAuthRequest) Set(val *InitiateOAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateOAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateOAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateOAuthRequest(val *InitiateOAuthRequest) *NullableInitiateOAuthRequest {
	return &NullableInitiateOAuthRequest{value: val, isSet: true}
}

func (v NullableInitiateOAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateOAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


