// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompleteOAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompleteOAuthRequest{}

// CompleteOAuthRequest Request to complete OAuth flow by exchanging authorization code for access token
type CompleteOAuthRequest struct {
	// Authorization code returned from OAuth provider
	Code string `json:"code"`
	Provider CloudSetupProvider `json:"provider"`
	// Session identifier from OAuth initiation
	SessionID string `json:"sessionID"`
}

type _CompleteOAuthRequest CompleteOAuthRequest

// NewCompleteOAuthRequest instantiates a new CompleteOAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompleteOAuthRequest(code string, provider CloudSetupProvider, sessionID string) *CompleteOAuthRequest {
	this := CompleteOAuthRequest{}
	this.Code = code
	this.Provider = provider
	this.SessionID = sessionID
	return &this
}

// NewCompleteOAuthRequestWithDefaults instantiates a new CompleteOAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompleteOAuthRequestWithDefaults() *CompleteOAuthRequest {
	this := CompleteOAuthRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *CompleteOAuthRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CompleteOAuthRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CompleteOAuthRequest) SetCode(v string) {
	o.Code = v
}

// GetProvider returns the Provider field value
func (o *CompleteOAuthRequest) GetProvider() CloudSetupProvider {
	if o == nil {
		var ret CloudSetupProvider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CompleteOAuthRequest) GetProviderOk() (*CloudSetupProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CompleteOAuthRequest) SetProvider(v CloudSetupProvider) {
	o.Provider = v
}

// GetSessionID returns the SessionID field value
func (o *CompleteOAuthRequest) GetSessionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value
// and a boolean to check if the value has been set.
func (o *CompleteOAuthRequest) GetSessionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionID, true
}

// SetSessionID sets field value
func (o *CompleteOAuthRequest) SetSessionID(v string) {
	o.SessionID = v
}

func (o CompleteOAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompleteOAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["provider"] = o.Provider
	toSerialize["sessionID"] = o.SessionID
	return toSerialize, nil
}

func (o *CompleteOAuthRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"provider",
		"sessionID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompleteOAuthRequest := _CompleteOAuthRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompleteOAuthRequest)

	if err != nil {
		return err
	}

	*o = CompleteOAuthRequest(varCompleteOAuthRequest)

	return err
}

type NullableCompleteOAuthRequest struct {
	value *CompleteOAuthRequest
	isSet bool
}

func (v NullableCompleteOAuthRequest) Get() *CompleteOAuthRequest {
	return v.value
}

func (v *NullableCompleteOAuthRequest) Set(val *CompleteOAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompleteOAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompleteOAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompleteOAuthRequest(val *CompleteOAuthRequest) *NullableCompleteOAuthRequest {
	return &NullableCompleteOAuthRequest{value: val, isSet: true}
}

func (v NullableCompleteOAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompleteOAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


