// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEnvironmentOpenRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentOpenRequestResponse{}

// CreateEnvironmentOpenRequestResponse Response body for create environment open request.
type CreateEnvironmentOpenRequestResponse struct {
	// List of change requests
	ChangeRequests []CreateEnvironmentOpenRequestResult `json:"changeRequests"`
}

type _CreateEnvironmentOpenRequestResponse CreateEnvironmentOpenRequestResponse

// NewCreateEnvironmentOpenRequestResponse instantiates a new CreateEnvironmentOpenRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentOpenRequestResponse(changeRequests []CreateEnvironmentOpenRequestResult) *CreateEnvironmentOpenRequestResponse {
	this := CreateEnvironmentOpenRequestResponse{}
	this.ChangeRequests = changeRequests
	return &this
}

// NewCreateEnvironmentOpenRequestResponseWithDefaults instantiates a new CreateEnvironmentOpenRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentOpenRequestResponseWithDefaults() *CreateEnvironmentOpenRequestResponse {
	this := CreateEnvironmentOpenRequestResponse{}
	return &this
}

// GetChangeRequests returns the ChangeRequests field value
func (o *CreateEnvironmentOpenRequestResponse) GetChangeRequests() []CreateEnvironmentOpenRequestResult {
	if o == nil {
		var ret []CreateEnvironmentOpenRequestResult
		return ret
	}

	return o.ChangeRequests
}

// GetChangeRequestsOk returns a tuple with the ChangeRequests field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentOpenRequestResponse) GetChangeRequestsOk() ([]CreateEnvironmentOpenRequestResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeRequests, true
}

// SetChangeRequests sets field value
func (o *CreateEnvironmentOpenRequestResponse) SetChangeRequests(v []CreateEnvironmentOpenRequestResult) {
	o.ChangeRequests = v
}

func (o CreateEnvironmentOpenRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentOpenRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["changeRequests"] = o.ChangeRequests
	return toSerialize, nil
}

func (o *CreateEnvironmentOpenRequestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"changeRequests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEnvironmentOpenRequestResponse := _CreateEnvironmentOpenRequestResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEnvironmentOpenRequestResponse)

	if err != nil {
		return err
	}

	*o = CreateEnvironmentOpenRequestResponse(varCreateEnvironmentOpenRequestResponse)

	return err
}

type NullableCreateEnvironmentOpenRequestResponse struct {
	value *CreateEnvironmentOpenRequestResponse
	isSet bool
}

func (v NullableCreateEnvironmentOpenRequestResponse) Get() *CreateEnvironmentOpenRequestResponse {
	return v.value
}

func (v *NullableCreateEnvironmentOpenRequestResponse) Set(val *CreateEnvironmentOpenRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentOpenRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentOpenRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentOpenRequestResponse(val *CreateEnvironmentOpenRequestResponse) *NullableCreateEnvironmentOpenRequestResponse {
	return &NullableCreateEnvironmentOpenRequestResponse{value: val, isSet: true}
}

func (v NullableCreateEnvironmentOpenRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentOpenRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


