// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrgEnvironment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgEnvironment{}

// OrgEnvironment OrgEnvironment represents an environment within an organization.
type OrgEnvironment struct {
	// The ISO 8601 timestamp when the environment was created.
	Created string `json:"created"`
	// The ISO 8601 timestamp when the environment was soft-deleted, or null if not deleted.
	DeletedAt *string `json:"deletedAt,omitempty"`
	// The unique identifier of the environment.
	Id string `json:"id"`
	Links *EnvironmentLinks `json:"links,omitempty"`
	// The ISO 8601 timestamp when the environment was last modified.
	Modified string `json:"modified"`
	// The name of the environment.
	Name *string `json:"name,omitempty"`
	// The login name of the organization that owns this environment.
	Organization *string `json:"organization,omitempty"`
	// The project name that contains this environment, if project-scoped.
	Project *string `json:"project,omitempty"`
	ReferrerMetadata EnvironmentReferrerMetadata `json:"referrerMetadata"`
	Settings EnvironmentSettings `json:"settings"`
	// User-defined key-value tags associated with the environment for organization and filtering.
	Tags map[string]string `json:"tags"`
}

type _OrgEnvironment OrgEnvironment

// NewOrgEnvironment instantiates a new OrgEnvironment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgEnvironment(created string, id string, modified string, referrerMetadata EnvironmentReferrerMetadata, settings EnvironmentSettings, tags map[string]string) *OrgEnvironment {
	this := OrgEnvironment{}
	this.Created = created
	this.Id = id
	this.Modified = modified
	this.ReferrerMetadata = referrerMetadata
	this.Settings = settings
	this.Tags = tags
	return &this
}

// NewOrgEnvironmentWithDefaults instantiates a new OrgEnvironment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgEnvironmentWithDefaults() *OrgEnvironment {
	this := OrgEnvironment{}
	return &this
}

// GetCreated returns the Created field value
func (o *OrgEnvironment) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *OrgEnvironment) SetCreated(v string) {
	o.Created = v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *OrgEnvironment) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt) {
		var ret string
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetDeletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *OrgEnvironment) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given string and assigns it to the DeletedAt field.
func (o *OrgEnvironment) SetDeletedAt(v string) {
	o.DeletedAt = &v
}

// GetId returns the Id field value
func (o *OrgEnvironment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrgEnvironment) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *OrgEnvironment) GetLinks() EnvironmentLinks {
	if o == nil || IsNil(o.Links) {
		var ret EnvironmentLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetLinksOk() (*EnvironmentLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *OrgEnvironment) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given EnvironmentLinks and assigns it to the Links field.
func (o *OrgEnvironment) SetLinks(v EnvironmentLinks) {
	o.Links = &v
}

// GetModified returns the Modified field value
func (o *OrgEnvironment) GetModified() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetModifiedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modified, true
}

// SetModified sets field value
func (o *OrgEnvironment) SetModified(v string) {
	o.Modified = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrgEnvironment) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrgEnvironment) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrgEnvironment) SetName(v string) {
	o.Name = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *OrgEnvironment) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *OrgEnvironment) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *OrgEnvironment) SetOrganization(v string) {
	o.Organization = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *OrgEnvironment) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *OrgEnvironment) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *OrgEnvironment) SetProject(v string) {
	o.Project = &v
}

// GetReferrerMetadata returns the ReferrerMetadata field value
func (o *OrgEnvironment) GetReferrerMetadata() EnvironmentReferrerMetadata {
	if o == nil {
		var ret EnvironmentReferrerMetadata
		return ret
	}

	return o.ReferrerMetadata
}

// GetReferrerMetadataOk returns a tuple with the ReferrerMetadata field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetReferrerMetadataOk() (*EnvironmentReferrerMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferrerMetadata, true
}

// SetReferrerMetadata sets field value
func (o *OrgEnvironment) SetReferrerMetadata(v EnvironmentReferrerMetadata) {
	o.ReferrerMetadata = v
}

// GetSettings returns the Settings field value
func (o *OrgEnvironment) GetSettings() EnvironmentSettings {
	if o == nil {
		var ret EnvironmentSettings
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetSettingsOk() (*EnvironmentSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settings, true
}

// SetSettings sets field value
func (o *OrgEnvironment) SetSettings(v EnvironmentSettings) {
	o.Settings = v
}

// GetTags returns the Tags field value
func (o *OrgEnvironment) GetTags() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *OrgEnvironment) GetTagsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *OrgEnvironment) SetTags(v map[string]string) {
	o.Tags = v
}

func (o OrgEnvironment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgEnvironment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	if !IsNil(o.DeletedAt) {
		toSerialize["deletedAt"] = o.DeletedAt
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	toSerialize["modified"] = o.Modified
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	toSerialize["referrerMetadata"] = o.ReferrerMetadata
	toSerialize["settings"] = o.Settings
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *OrgEnvironment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"id",
		"modified",
		"referrerMetadata",
		"settings",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgEnvironment := _OrgEnvironment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgEnvironment)

	if err != nil {
		return err
	}

	*o = OrgEnvironment(varOrgEnvironment)

	return err
}

type NullableOrgEnvironment struct {
	value *OrgEnvironment
	isSet bool
}

func (v NullableOrgEnvironment) Get() *OrgEnvironment {
	return v.value
}

func (v *NullableOrgEnvironment) Set(val *OrgEnvironment) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgEnvironment(val *OrgEnvironment) *NullableOrgEnvironment {
	return &NullableOrgEnvironment{value: val, isSet: true}
}

func (v NullableOrgEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


