// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentSettings{}

// EnvironmentSettings EnvironmentSettings contains settings that control the behavior of an environment.
type EnvironmentSettings struct {
	// Whether the environment is protected from deletion.
	DeletionProtected bool `json:"deletionProtected"`
}

type _EnvironmentSettings EnvironmentSettings

// NewEnvironmentSettings instantiates a new EnvironmentSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentSettings(deletionProtected bool) *EnvironmentSettings {
	this := EnvironmentSettings{}
	this.DeletionProtected = deletionProtected
	return &this
}

// NewEnvironmentSettingsWithDefaults instantiates a new EnvironmentSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentSettingsWithDefaults() *EnvironmentSettings {
	this := EnvironmentSettings{}
	return &this
}

// GetDeletionProtected returns the DeletionProtected field value
func (o *EnvironmentSettings) GetDeletionProtected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DeletionProtected
}

// GetDeletionProtectedOk returns a tuple with the DeletionProtected field value
// and a boolean to check if the value has been set.
func (o *EnvironmentSettings) GetDeletionProtectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletionProtected, true
}

// SetDeletionProtected sets field value
func (o *EnvironmentSettings) SetDeletionProtected(v bool) {
	o.DeletionProtected = v
}

func (o EnvironmentSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deletionProtected"] = o.DeletionProtected
	return toSerialize, nil
}

func (o *EnvironmentSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deletionProtected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentSettings := _EnvironmentSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentSettings)

	if err != nil {
		return err
	}

	*o = EnvironmentSettings(varEnvironmentSettings)

	return err
}

type NullableEnvironmentSettings struct {
	value *EnvironmentSettings
	isSet bool
}

func (v NullableEnvironmentSettings) Get() *EnvironmentSettings {
	return v.value
}

func (v *NullableEnvironmentSettings) Set(val *EnvironmentSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentSettings(val *EnvironmentSettings) *NullableEnvironmentSettings {
	return &NullableEnvironmentSettings{value: val, isSet: true}
}

func (v NullableEnvironmentSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


