// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListScheduledActionHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListScheduledActionHistoryResponse{}

// ListScheduledActionHistoryResponse ListScheduledActionHistoryResponse is the API response when a scheduled action history is listed.
type ListScheduledActionHistoryResponse struct {
	// The list of scheduled action history events
	ScheduleHistoryEvents []ScheduledActionHistoryEvent `json:"scheduleHistoryEvents"`
}

type _ListScheduledActionHistoryResponse ListScheduledActionHistoryResponse

// NewListScheduledActionHistoryResponse instantiates a new ListScheduledActionHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListScheduledActionHistoryResponse(scheduleHistoryEvents []ScheduledActionHistoryEvent) *ListScheduledActionHistoryResponse {
	this := ListScheduledActionHistoryResponse{}
	this.ScheduleHistoryEvents = scheduleHistoryEvents
	return &this
}

// NewListScheduledActionHistoryResponseWithDefaults instantiates a new ListScheduledActionHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListScheduledActionHistoryResponseWithDefaults() *ListScheduledActionHistoryResponse {
	this := ListScheduledActionHistoryResponse{}
	return &this
}

// GetScheduleHistoryEvents returns the ScheduleHistoryEvents field value
func (o *ListScheduledActionHistoryResponse) GetScheduleHistoryEvents() []ScheduledActionHistoryEvent {
	if o == nil {
		var ret []ScheduledActionHistoryEvent
		return ret
	}

	return o.ScheduleHistoryEvents
}

// GetScheduleHistoryEventsOk returns a tuple with the ScheduleHistoryEvents field value
// and a boolean to check if the value has been set.
func (o *ListScheduledActionHistoryResponse) GetScheduleHistoryEventsOk() ([]ScheduledActionHistoryEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScheduleHistoryEvents, true
}

// SetScheduleHistoryEvents sets field value
func (o *ListScheduledActionHistoryResponse) SetScheduleHistoryEvents(v []ScheduledActionHistoryEvent) {
	o.ScheduleHistoryEvents = v
}

func (o ListScheduledActionHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListScheduledActionHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scheduleHistoryEvents"] = o.ScheduleHistoryEvents
	return toSerialize, nil
}

func (o *ListScheduledActionHistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scheduleHistoryEvents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListScheduledActionHistoryResponse := _ListScheduledActionHistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListScheduledActionHistoryResponse)

	if err != nil {
		return err
	}

	*o = ListScheduledActionHistoryResponse(varListScheduledActionHistoryResponse)

	return err
}

type NullableListScheduledActionHistoryResponse struct {
	value *ListScheduledActionHistoryResponse
	isSet bool
}

func (v NullableListScheduledActionHistoryResponse) Get() *ListScheduledActionHistoryResponse {
	return v.value
}

func (v *NullableListScheduledActionHistoryResponse) Set(val *ListScheduledActionHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListScheduledActionHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListScheduledActionHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListScheduledActionHistoryResponse(val *ListScheduledActionHistoryResponse) *NullableListScheduledActionHistoryResponse {
	return &NullableListScheduledActionHistoryResponse{value: val, isSet: true}
}

func (v NullableListScheduledActionHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListScheduledActionHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


