// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AWSSSOInitiateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AWSSSOInitiateRequest{}

// AWSSSOInitiateRequest Request to initiate AWS SSO flow
type AWSSSOInitiateRequest struct {
	// The AWS SSO Region
	Region string `json:"region"`
	// The AWS SSO Start URL
	StartUrl string `json:"startUrl"`
}

type _AWSSSOInitiateRequest AWSSSOInitiateRequest

// NewAWSSSOInitiateRequest instantiates a new AWSSSOInitiateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSSSOInitiateRequest(region string, startUrl string) *AWSSSOInitiateRequest {
	this := AWSSSOInitiateRequest{}
	this.Region = region
	this.StartUrl = startUrl
	return &this
}

// NewAWSSSOInitiateRequestWithDefaults instantiates a new AWSSSOInitiateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSSSOInitiateRequestWithDefaults() *AWSSSOInitiateRequest {
	this := AWSSSOInitiateRequest{}
	return &this
}

// GetRegion returns the Region field value
func (o *AWSSSOInitiateRequest) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *AWSSSOInitiateRequest) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *AWSSSOInitiateRequest) SetRegion(v string) {
	o.Region = v
}

// GetStartUrl returns the StartUrl field value
func (o *AWSSSOInitiateRequest) GetStartUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartUrl
}

// GetStartUrlOk returns a tuple with the StartUrl field value
// and a boolean to check if the value has been set.
func (o *AWSSSOInitiateRequest) GetStartUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartUrl, true
}

// SetStartUrl sets field value
func (o *AWSSSOInitiateRequest) SetStartUrl(v string) {
	o.StartUrl = v
}

func (o AWSSSOInitiateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AWSSSOInitiateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["region"] = o.Region
	toSerialize["startUrl"] = o.StartUrl
	return toSerialize, nil
}

func (o *AWSSSOInitiateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"region",
		"startUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAWSSSOInitiateRequest := _AWSSSOInitiateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAWSSSOInitiateRequest)

	if err != nil {
		return err
	}

	*o = AWSSSOInitiateRequest(varAWSSSOInitiateRequest)

	return err
}

type NullableAWSSSOInitiateRequest struct {
	value *AWSSSOInitiateRequest
	isSet bool
}

func (v NullableAWSSSOInitiateRequest) Get() *AWSSSOInitiateRequest {
	return v.value
}

func (v *NullableAWSSSOInitiateRequest) Set(val *AWSSSOInitiateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSSSOInitiateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSSSOInitiateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSSSOInitiateRequest(val *AWSSSOInitiateRequest) *NullableAWSSSOInitiateRequest {
	return &NullableAWSSSOInitiateRequest{value: val, isSet: true}
}

func (v NullableAWSSSOInitiateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSSSOInitiateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


