// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateEnvironmentResponse{}

// RotateEnvironmentResponse Response from a secret rotation operation on an environment.
type RotateEnvironmentResponse struct {
	// Diagnostics generated during the rotation operation.
	Diagnostics []EnvironmentDiagnostic `json:"diagnostics,omitempty"`
	// The unique identifier for this rotation operation.
	Id string `json:"id"`
	SecretRotationEvent SecretRotationEvent `json:"secretRotationEvent"`
}

type _RotateEnvironmentResponse RotateEnvironmentResponse

// NewRotateEnvironmentResponse instantiates a new RotateEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateEnvironmentResponse(id string, secretRotationEvent SecretRotationEvent) *RotateEnvironmentResponse {
	this := RotateEnvironmentResponse{}
	this.Id = id
	this.SecretRotationEvent = secretRotationEvent
	return &this
}

// NewRotateEnvironmentResponseWithDefaults instantiates a new RotateEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateEnvironmentResponseWithDefaults() *RotateEnvironmentResponse {
	this := RotateEnvironmentResponse{}
	return &this
}

// GetDiagnostics returns the Diagnostics field value if set, zero value otherwise.
func (o *RotateEnvironmentResponse) GetDiagnostics() []EnvironmentDiagnostic {
	if o == nil || IsNil(o.Diagnostics) {
		var ret []EnvironmentDiagnostic
		return ret
	}
	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateEnvironmentResponse) GetDiagnosticsOk() ([]EnvironmentDiagnostic, bool) {
	if o == nil || IsNil(o.Diagnostics) {
		return nil, false
	}
	return o.Diagnostics, true
}

// HasDiagnostics returns a boolean if a field has been set.
func (o *RotateEnvironmentResponse) HasDiagnostics() bool {
	if o != nil && !IsNil(o.Diagnostics) {
		return true
	}

	return false
}

// SetDiagnostics gets a reference to the given []EnvironmentDiagnostic and assigns it to the Diagnostics field.
func (o *RotateEnvironmentResponse) SetDiagnostics(v []EnvironmentDiagnostic) {
	o.Diagnostics = v
}

// GetId returns the Id field value
func (o *RotateEnvironmentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RotateEnvironmentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RotateEnvironmentResponse) SetId(v string) {
	o.Id = v
}

// GetSecretRotationEvent returns the SecretRotationEvent field value
func (o *RotateEnvironmentResponse) GetSecretRotationEvent() SecretRotationEvent {
	if o == nil {
		var ret SecretRotationEvent
		return ret
	}

	return o.SecretRotationEvent
}

// GetSecretRotationEventOk returns a tuple with the SecretRotationEvent field value
// and a boolean to check if the value has been set.
func (o *RotateEnvironmentResponse) GetSecretRotationEventOk() (*SecretRotationEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretRotationEvent, true
}

// SetSecretRotationEvent sets field value
func (o *RotateEnvironmentResponse) SetSecretRotationEvent(v SecretRotationEvent) {
	o.SecretRotationEvent = v
}

func (o RotateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Diagnostics) {
		toSerialize["diagnostics"] = o.Diagnostics
	}
	toSerialize["id"] = o.Id
	toSerialize["secretRotationEvent"] = o.SecretRotationEvent
	return toSerialize, nil
}

func (o *RotateEnvironmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"secretRotationEvent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateEnvironmentResponse := _RotateEnvironmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateEnvironmentResponse)

	if err != nil {
		return err
	}

	*o = RotateEnvironmentResponse(varRotateEnvironmentResponse)

	return err
}

type NullableRotateEnvironmentResponse struct {
	value *RotateEnvironmentResponse
	isSet bool
}

func (v NullableRotateEnvironmentResponse) Get() *RotateEnvironmentResponse {
	return v.value
}

func (v *NullableRotateEnvironmentResponse) Set(val *RotateEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateEnvironmentResponse(val *RotateEnvironmentResponse) *NullableRotateEnvironmentResponse {
	return &NullableRotateEnvironmentResponse{value: val, isSet: true}
}

func (v NullableRotateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


