// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListRotatorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRotatorsResponse{}

// ListRotatorsResponse Response containing a list of available secret rotators.
type ListRotatorsResponse struct {
	// The list of rotator names
	Rotators []string `json:"rotators"`
}

type _ListRotatorsResponse ListRotatorsResponse

// NewListRotatorsResponse instantiates a new ListRotatorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRotatorsResponse(rotators []string) *ListRotatorsResponse {
	this := ListRotatorsResponse{}
	this.Rotators = rotators
	return &this
}

// NewListRotatorsResponseWithDefaults instantiates a new ListRotatorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRotatorsResponseWithDefaults() *ListRotatorsResponse {
	this := ListRotatorsResponse{}
	return &this
}

// GetRotators returns the Rotators field value
func (o *ListRotatorsResponse) GetRotators() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Rotators
}

// GetRotatorsOk returns a tuple with the Rotators field value
// and a boolean to check if the value has been set.
func (o *ListRotatorsResponse) GetRotatorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rotators, true
}

// SetRotators sets field value
func (o *ListRotatorsResponse) SetRotators(v []string) {
	o.Rotators = v
}

func (o ListRotatorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRotatorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rotators"] = o.Rotators
	return toSerialize, nil
}

func (o *ListRotatorsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rotators",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListRotatorsResponse := _ListRotatorsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListRotatorsResponse)

	if err != nil {
		return err
	}

	*o = ListRotatorsResponse(varListRotatorsResponse)

	return err
}

type NullableListRotatorsResponse struct {
	value *ListRotatorsResponse
	isSet bool
}

func (v NullableListRotatorsResponse) Get() *ListRotatorsResponse {
	return v.value
}

func (v *NullableListRotatorsResponse) Set(val *ListRotatorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRotatorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRotatorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRotatorsResponse(val *ListRotatorsResponse) *NullableListRotatorsResponse {
	return &NullableListRotatorsResponse{value: val, isSet: true}
}

func (v NullableListRotatorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRotatorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


