// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GetChangeRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChangeRequestResponse{}

// GetChangeRequestResponse struct for GetChangeRequestResponse
type GetChangeRequestResponse struct {
	// The change request ID
	Id string `json:"id"`
	// The current status of the change request
	Status string `json:"status"`
	// The organization ID
	OrgID string `json:"orgID"`
	CreatedBy UserInfo `json:"createdBy"`
	// The description/justification for this change request
	Description string `json:"description"`
	// When this change request was created
	CreatedAt time.Time `json:"createdAt"`
	Entity TargetEntity `json:"entity"`
	// The current revision number
	LatestRevisionNumber int64 `json:"latestRevisionNumber"`
	GateEvaluation ChangeRequestGateEvaluation `json:"gateEvaluation"`
}

type _GetChangeRequestResponse GetChangeRequestResponse

// NewGetChangeRequestResponse instantiates a new GetChangeRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChangeRequestResponse(id string, status string, orgID string, createdBy UserInfo, description string, createdAt time.Time, entity TargetEntity, latestRevisionNumber int64, gateEvaluation ChangeRequestGateEvaluation) *GetChangeRequestResponse {
	this := GetChangeRequestResponse{}
	this.Id = id
	this.Status = status
	this.OrgID = orgID
	this.CreatedBy = createdBy
	this.Description = description
	this.CreatedAt = createdAt
	this.Entity = entity
	this.LatestRevisionNumber = latestRevisionNumber
	this.GateEvaluation = gateEvaluation
	return &this
}

// NewGetChangeRequestResponseWithDefaults instantiates a new GetChangeRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChangeRequestResponseWithDefaults() *GetChangeRequestResponse {
	this := GetChangeRequestResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetChangeRequestResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetChangeRequestResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *GetChangeRequestResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetChangeRequestResponse) SetStatus(v string) {
	o.Status = v
}

// GetOrgID returns the OrgID field value
func (o *GetChangeRequestResponse) GetOrgID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgID
}

// GetOrgIDOk returns a tuple with the OrgID field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetOrgIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgID, true
}

// SetOrgID sets field value
func (o *GetChangeRequestResponse) SetOrgID(v string) {
	o.OrgID = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *GetChangeRequestResponse) GetCreatedBy() UserInfo {
	if o == nil {
		var ret UserInfo
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetCreatedByOk() (*UserInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *GetChangeRequestResponse) SetCreatedBy(v UserInfo) {
	o.CreatedBy = v
}

// GetDescription returns the Description field value
func (o *GetChangeRequestResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetChangeRequestResponse) SetDescription(v string) {
	o.Description = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetChangeRequestResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetChangeRequestResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEntity returns the Entity field value
func (o *GetChangeRequestResponse) GetEntity() TargetEntity {
	if o == nil {
		var ret TargetEntity
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetEntityOk() (*TargetEntity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *GetChangeRequestResponse) SetEntity(v TargetEntity) {
	o.Entity = v
}

// GetLatestRevisionNumber returns the LatestRevisionNumber field value
func (o *GetChangeRequestResponse) GetLatestRevisionNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LatestRevisionNumber
}

// GetLatestRevisionNumberOk returns a tuple with the LatestRevisionNumber field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetLatestRevisionNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestRevisionNumber, true
}

// SetLatestRevisionNumber sets field value
func (o *GetChangeRequestResponse) SetLatestRevisionNumber(v int64) {
	o.LatestRevisionNumber = v
}

// GetGateEvaluation returns the GateEvaluation field value
func (o *GetChangeRequestResponse) GetGateEvaluation() ChangeRequestGateEvaluation {
	if o == nil {
		var ret ChangeRequestGateEvaluation
		return ret
	}

	return o.GateEvaluation
}

// GetGateEvaluationOk returns a tuple with the GateEvaluation field value
// and a boolean to check if the value has been set.
func (o *GetChangeRequestResponse) GetGateEvaluationOk() (*ChangeRequestGateEvaluation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GateEvaluation, true
}

// SetGateEvaluation sets field value
func (o *GetChangeRequestResponse) SetGateEvaluation(v ChangeRequestGateEvaluation) {
	o.GateEvaluation = v
}

func (o GetChangeRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChangeRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["orgID"] = o.OrgID
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["description"] = o.Description
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["entity"] = o.Entity
	toSerialize["latestRevisionNumber"] = o.LatestRevisionNumber
	toSerialize["gateEvaluation"] = o.GateEvaluation
	return toSerialize, nil
}

func (o *GetChangeRequestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"orgID",
		"createdBy",
		"description",
		"createdAt",
		"entity",
		"latestRevisionNumber",
		"gateEvaluation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetChangeRequestResponse := _GetChangeRequestResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Allow unknown fields to be lenient with API responses that may include extra fields
	err = decoder.Decode(&varGetChangeRequestResponse)

	if err != nil {
		return err
	}

	*o = GetChangeRequestResponse(varGetChangeRequestResponse)

	return err
}

type NullableGetChangeRequestResponse struct {
	value *GetChangeRequestResponse
	isSet bool
}

func (v NullableGetChangeRequestResponse) Get() *GetChangeRequestResponse {
	return v.value
}

func (v *NullableGetChangeRequestResponse) Set(val *GetChangeRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChangeRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChangeRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChangeRequestResponse(val *GetChangeRequestResponse) *NullableGetChangeRequestResponse {
	return &NullableGetChangeRequestResponse{value: val, isSet: true}
}

func (v NullableGetChangeRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChangeRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


