// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the EnvironmentReferrer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentReferrer{}

// EnvironmentReferrer An EnvironmentReferrer represents an entity that refers to an environment.
type EnvironmentReferrer struct {
	Environment *EnvironmentImportReferrer `json:"environment,omitempty"`
	InsightsAccount *EnvironmentInsightsAccountReferrer `json:"insightsAccount,omitempty"`
	Stack *EnvironmentStackReferrer `json:"stack,omitempty"`
}

// NewEnvironmentReferrer instantiates a new EnvironmentReferrer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentReferrer() *EnvironmentReferrer {
	this := EnvironmentReferrer{}
	return &this
}

// NewEnvironmentReferrerWithDefaults instantiates a new EnvironmentReferrer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentReferrerWithDefaults() *EnvironmentReferrer {
	this := EnvironmentReferrer{}
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *EnvironmentReferrer) GetEnvironment() EnvironmentImportReferrer {
	if o == nil || IsNil(o.Environment) {
		var ret EnvironmentImportReferrer
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrer) GetEnvironmentOk() (*EnvironmentImportReferrer, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *EnvironmentReferrer) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given EnvironmentImportReferrer and assigns it to the Environment field.
func (o *EnvironmentReferrer) SetEnvironment(v EnvironmentImportReferrer) {
	o.Environment = &v
}

// GetInsightsAccount returns the InsightsAccount field value if set, zero value otherwise.
func (o *EnvironmentReferrer) GetInsightsAccount() EnvironmentInsightsAccountReferrer {
	if o == nil || IsNil(o.InsightsAccount) {
		var ret EnvironmentInsightsAccountReferrer
		return ret
	}
	return *o.InsightsAccount
}

// GetInsightsAccountOk returns a tuple with the InsightsAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrer) GetInsightsAccountOk() (*EnvironmentInsightsAccountReferrer, bool) {
	if o == nil || IsNil(o.InsightsAccount) {
		return nil, false
	}
	return o.InsightsAccount, true
}

// HasInsightsAccount returns a boolean if a field has been set.
func (o *EnvironmentReferrer) HasInsightsAccount() bool {
	if o != nil && !IsNil(o.InsightsAccount) {
		return true
	}

	return false
}

// SetInsightsAccount gets a reference to the given EnvironmentInsightsAccountReferrer and assigns it to the InsightsAccount field.
func (o *EnvironmentReferrer) SetInsightsAccount(v EnvironmentInsightsAccountReferrer) {
	o.InsightsAccount = &v
}

// GetStack returns the Stack field value if set, zero value otherwise.
func (o *EnvironmentReferrer) GetStack() EnvironmentStackReferrer {
	if o == nil || IsNil(o.Stack) {
		var ret EnvironmentStackReferrer
		return ret
	}
	return *o.Stack
}

// GetStackOk returns a tuple with the Stack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrer) GetStackOk() (*EnvironmentStackReferrer, bool) {
	if o == nil || IsNil(o.Stack) {
		return nil, false
	}
	return o.Stack, true
}

// HasStack returns a boolean if a field has been set.
func (o *EnvironmentReferrer) HasStack() bool {
	if o != nil && !IsNil(o.Stack) {
		return true
	}

	return false
}

// SetStack gets a reference to the given EnvironmentStackReferrer and assigns it to the Stack field.
func (o *EnvironmentReferrer) SetStack(v EnvironmentStackReferrer) {
	o.Stack = &v
}

func (o EnvironmentReferrer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentReferrer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.InsightsAccount) {
		toSerialize["insightsAccount"] = o.InsightsAccount
	}
	if !IsNil(o.Stack) {
		toSerialize["stack"] = o.Stack
	}
	return toSerialize, nil
}

type NullableEnvironmentReferrer struct {
	value *EnvironmentReferrer
	isSet bool
}

func (v NullableEnvironmentReferrer) Get() *EnvironmentReferrer {
	return v.value
}

func (v *NullableEnvironmentReferrer) Set(val *EnvironmentReferrer) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentReferrer) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentReferrer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentReferrer(val *EnvironmentReferrer) *NullableEnvironmentReferrer {
	return &NullableEnvironmentReferrer{value: val, isSet: true}
}

func (v NullableEnvironmentReferrer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentReferrer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


