// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the ApprovalRuleEligibilityOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalRuleEligibilityOutput{}

// ApprovalRuleEligibilityOutput struct for ApprovalRuleEligibilityOutput
type ApprovalRuleEligibilityOutput struct {
	EligibilityType *string `json:"eligibilityType,omitempty"`
}

// NewApprovalRuleEligibilityOutput instantiates a new ApprovalRuleEligibilityOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalRuleEligibilityOutput() *ApprovalRuleEligibilityOutput {
	this := ApprovalRuleEligibilityOutput{}
	return &this
}

// NewApprovalRuleEligibilityOutputWithDefaults instantiates a new ApprovalRuleEligibilityOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalRuleEligibilityOutputWithDefaults() *ApprovalRuleEligibilityOutput {
	this := ApprovalRuleEligibilityOutput{}
	return &this
}

// GetEligibilityType returns the EligibilityType field value if set, zero value otherwise.
func (o *ApprovalRuleEligibilityOutput) GetEligibilityType() string {
	if o == nil || IsNil(o.EligibilityType) {
		var ret string
		return ret
	}
	return *o.EligibilityType
}

// GetEligibilityTypeOk returns a tuple with the EligibilityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalRuleEligibilityOutput) GetEligibilityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EligibilityType) {
		return nil, false
	}
	return o.EligibilityType, true
}

// HasEligibilityType returns a boolean if a field has been set.
func (o *ApprovalRuleEligibilityOutput) HasEligibilityType() bool {
	if o != nil && !IsNil(o.EligibilityType) {
		return true
	}

	return false
}

// SetEligibilityType gets a reference to the given string and assigns it to the EligibilityType field.
func (o *ApprovalRuleEligibilityOutput) SetEligibilityType(v string) {
	o.EligibilityType = &v
}

func (o ApprovalRuleEligibilityOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalRuleEligibilityOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EligibilityType) {
		toSerialize["eligibilityType"] = o.EligibilityType
	}
	return toSerialize, nil
}

type NullableApprovalRuleEligibilityOutput struct {
	value *ApprovalRuleEligibilityOutput
	isSet bool
}

func (v NullableApprovalRuleEligibilityOutput) Get() *ApprovalRuleEligibilityOutput {
	return v.value
}

func (v *NullableApprovalRuleEligibilityOutput) Set(val *ApprovalRuleEligibilityOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalRuleEligibilityOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalRuleEligibilityOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalRuleEligibilityOutput(val *ApprovalRuleEligibilityOutput) *NullableApprovalRuleEligibilityOutput {
	return &NullableApprovalRuleEligibilityOutput{value: val, isSet: true}
}

func (v NullableApprovalRuleEligibilityOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalRuleEligibilityOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


