// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeGateApprovalRuleOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeGateApprovalRuleOutput{}

// ChangeGateApprovalRuleOutput struct for ChangeGateApprovalRuleOutput
type ChangeGateApprovalRuleOutput struct {
	ChangeGateRuleOutput
	// Number of approvals required
	NumApprovalsRequired int64 `json:"numApprovalsRequired"`
	// Whether self approval is allowed
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty"`
	// Whether reapproval is required when the change request is modified
	RequireReapprovalOnChange *bool `json:"requireReapprovalOnChange,omitempty"`
	// List of eligible approvers
	EligibleApprovers []ApprovalRuleEligibilityOutput `json:"eligibleApprovers"`
}

type _ChangeGateApprovalRuleOutput ChangeGateApprovalRuleOutput

// NewChangeGateApprovalRuleOutput instantiates a new ChangeGateApprovalRuleOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeGateApprovalRuleOutput(numApprovalsRequired int64, eligibleApprovers []ApprovalRuleEligibilityOutput) *ChangeGateApprovalRuleOutput {
	this := ChangeGateApprovalRuleOutput{}
	this.NumApprovalsRequired = numApprovalsRequired
	this.EligibleApprovers = eligibleApprovers
	return &this
}

// NewChangeGateApprovalRuleOutputWithDefaults instantiates a new ChangeGateApprovalRuleOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeGateApprovalRuleOutputWithDefaults() *ChangeGateApprovalRuleOutput {
	this := ChangeGateApprovalRuleOutput{}
	return &this
}

// GetNumApprovalsRequired returns the NumApprovalsRequired field value
func (o *ChangeGateApprovalRuleOutput) GetNumApprovalsRequired() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumApprovalsRequired
}

// GetNumApprovalsRequiredOk returns a tuple with the NumApprovalsRequired field value
// and a boolean to check if the value has been set.
func (o *ChangeGateApprovalRuleOutput) GetNumApprovalsRequiredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumApprovalsRequired, true
}

// SetNumApprovalsRequired sets field value
func (o *ChangeGateApprovalRuleOutput) SetNumApprovalsRequired(v int64) {
	o.NumApprovalsRequired = v
}

// GetAllowSelfApproval returns the AllowSelfApproval field value if set, zero value otherwise.
func (o *ChangeGateApprovalRuleOutput) GetAllowSelfApproval() bool {
	if o == nil || IsNil(o.AllowSelfApproval) {
		var ret bool
		return ret
	}
	return *o.AllowSelfApproval
}

// GetAllowSelfApprovalOk returns a tuple with the AllowSelfApproval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeGateApprovalRuleOutput) GetAllowSelfApprovalOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowSelfApproval) {
		return nil, false
	}
	return o.AllowSelfApproval, true
}

// HasAllowSelfApproval returns a boolean if a field has been set.
func (o *ChangeGateApprovalRuleOutput) HasAllowSelfApproval() bool {
	if o != nil && !IsNil(o.AllowSelfApproval) {
		return true
	}

	return false
}

// SetAllowSelfApproval gets a reference to the given bool and assigns it to the AllowSelfApproval field.
func (o *ChangeGateApprovalRuleOutput) SetAllowSelfApproval(v bool) {
	o.AllowSelfApproval = &v
}

// GetRequireReapprovalOnChange returns the RequireReapprovalOnChange field value if set, zero value otherwise.
func (o *ChangeGateApprovalRuleOutput) GetRequireReapprovalOnChange() bool {
	if o == nil || IsNil(o.RequireReapprovalOnChange) {
		var ret bool
		return ret
	}
	return *o.RequireReapprovalOnChange
}

// GetRequireReapprovalOnChangeOk returns a tuple with the RequireReapprovalOnChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeGateApprovalRuleOutput) GetRequireReapprovalOnChangeOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireReapprovalOnChange) {
		return nil, false
	}
	return o.RequireReapprovalOnChange, true
}

// HasRequireReapprovalOnChange returns a boolean if a field has been set.
func (o *ChangeGateApprovalRuleOutput) HasRequireReapprovalOnChange() bool {
	if o != nil && !IsNil(o.RequireReapprovalOnChange) {
		return true
	}

	return false
}

// SetRequireReapprovalOnChange gets a reference to the given bool and assigns it to the RequireReapprovalOnChange field.
func (o *ChangeGateApprovalRuleOutput) SetRequireReapprovalOnChange(v bool) {
	o.RequireReapprovalOnChange = &v
}

// GetEligibleApprovers returns the EligibleApprovers field value
func (o *ChangeGateApprovalRuleOutput) GetEligibleApprovers() []ApprovalRuleEligibilityOutput {
	if o == nil {
		var ret []ApprovalRuleEligibilityOutput
		return ret
	}

	return o.EligibleApprovers
}

// GetEligibleApproversOk returns a tuple with the EligibleApprovers field value
// and a boolean to check if the value has been set.
func (o *ChangeGateApprovalRuleOutput) GetEligibleApproversOk() ([]ApprovalRuleEligibilityOutput, bool) {
	if o == nil {
		return nil, false
	}
	return o.EligibleApprovers, true
}

// SetEligibleApprovers sets field value
func (o *ChangeGateApprovalRuleOutput) SetEligibleApprovers(v []ApprovalRuleEligibilityOutput) {
	o.EligibleApprovers = v
}

func (o ChangeGateApprovalRuleOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeGateApprovalRuleOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedChangeGateRuleOutput, errChangeGateRuleOutput := json.Marshal(o.ChangeGateRuleOutput)
	if errChangeGateRuleOutput != nil {
		return map[string]interface{}{}, errChangeGateRuleOutput
	}
	errChangeGateRuleOutput = json.Unmarshal([]byte(serializedChangeGateRuleOutput), &toSerialize)
	if errChangeGateRuleOutput != nil {
		return map[string]interface{}{}, errChangeGateRuleOutput
	}
	toSerialize["numApprovalsRequired"] = o.NumApprovalsRequired
	if !IsNil(o.AllowSelfApproval) {
		toSerialize["allowSelfApproval"] = o.AllowSelfApproval
	}
	if !IsNil(o.RequireReapprovalOnChange) {
		toSerialize["requireReapprovalOnChange"] = o.RequireReapprovalOnChange
	}
	toSerialize["eligibleApprovers"] = o.EligibleApprovers
	return toSerialize, nil
}

func (o *ChangeGateApprovalRuleOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"numApprovalsRequired",
		"eligibleApprovers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeGateApprovalRuleOutput := _ChangeGateApprovalRuleOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Allow unknown fields to be lenient with API responses that may include extra fields
	err = decoder.Decode(&varChangeGateApprovalRuleOutput)

	if err != nil {
		return err
	}

	*o = ChangeGateApprovalRuleOutput(varChangeGateApprovalRuleOutput)

	return err
}

type NullableChangeGateApprovalRuleOutput struct {
	value *ChangeGateApprovalRuleOutput
	isSet bool
}

func (v NullableChangeGateApprovalRuleOutput) Get() *ChangeGateApprovalRuleOutput {
	return v.value
}

func (v *NullableChangeGateApprovalRuleOutput) Set(val *ChangeGateApprovalRuleOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeGateApprovalRuleOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeGateApprovalRuleOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeGateApprovalRuleOutput(val *ChangeGateApprovalRuleOutput) *NullableChangeGateApprovalRuleOutput {
	return &NullableChangeGateApprovalRuleOutput{value: val, isSet: true}
}

func (v NullableChangeGateApprovalRuleOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeGateApprovalRuleOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


