// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AWSSSOSetupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AWSSSOSetupRequest{}

// AWSSSOSetupRequest Request to setup AWS from AWS SSO
type AWSSSOSetupRequest struct {
	// The AWS account id
	AccountId string `json:"accountId"`
	// The AWS account role name
	AccountRoleName string `json:"accountRoleName"`
	// Name of IAM Role for OIDC
	OidcRoleName string `json:"oidcRoleName"`
	// ARN of the IAM policy to attach to the role
	PolicyArn string `json:"policyArn"`
	// The AWS SSO Region
	Region string `json:"region"`
	// The auth session id
	SessionId string `json:"sessionId"`
}

type _AWSSSOSetupRequest AWSSSOSetupRequest

// NewAWSSSOSetupRequest instantiates a new AWSSSOSetupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSSSOSetupRequest(accountId string, accountRoleName string, oidcRoleName string, policyArn string, region string, sessionId string) *AWSSSOSetupRequest {
	this := AWSSSOSetupRequest{}
	this.AccountId = accountId
	this.AccountRoleName = accountRoleName
	this.OidcRoleName = oidcRoleName
	this.PolicyArn = policyArn
	this.Region = region
	this.SessionId = sessionId
	return &this
}

// NewAWSSSOSetupRequestWithDefaults instantiates a new AWSSSOSetupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSSSOSetupRequestWithDefaults() *AWSSSOSetupRequest {
	this := AWSSSOSetupRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AWSSSOSetupRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AWSSSOSetupRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetAccountRoleName returns the AccountRoleName field value
func (o *AWSSSOSetupRequest) GetAccountRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountRoleName
}

// GetAccountRoleNameOk returns a tuple with the AccountRoleName field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetAccountRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountRoleName, true
}

// SetAccountRoleName sets field value
func (o *AWSSSOSetupRequest) SetAccountRoleName(v string) {
	o.AccountRoleName = v
}

// GetOidcRoleName returns the OidcRoleName field value
func (o *AWSSSOSetupRequest) GetOidcRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OidcRoleName
}

// GetOidcRoleNameOk returns a tuple with the OidcRoleName field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetOidcRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OidcRoleName, true
}

// SetOidcRoleName sets field value
func (o *AWSSSOSetupRequest) SetOidcRoleName(v string) {
	o.OidcRoleName = v
}

// GetPolicyArn returns the PolicyArn field value
func (o *AWSSSOSetupRequest) GetPolicyArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyArn
}

// GetPolicyArnOk returns a tuple with the PolicyArn field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetPolicyArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyArn, true
}

// SetPolicyArn sets field value
func (o *AWSSSOSetupRequest) SetPolicyArn(v string) {
	o.PolicyArn = v
}

// GetRegion returns the Region field value
func (o *AWSSSOSetupRequest) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *AWSSSOSetupRequest) SetRegion(v string) {
	o.Region = v
}

// GetSessionId returns the SessionId field value
func (o *AWSSSOSetupRequest) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *AWSSSOSetupRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *AWSSSOSetupRequest) SetSessionId(v string) {
	o.SessionId = v
}

func (o AWSSSOSetupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AWSSSOSetupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["accountRoleName"] = o.AccountRoleName
	toSerialize["oidcRoleName"] = o.OidcRoleName
	toSerialize["policyArn"] = o.PolicyArn
	toSerialize["region"] = o.Region
	toSerialize["sessionId"] = o.SessionId
	return toSerialize, nil
}

func (o *AWSSSOSetupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"accountRoleName",
		"oidcRoleName",
		"policyArn",
		"region",
		"sessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAWSSSOSetupRequest := _AWSSSOSetupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAWSSSOSetupRequest)

	if err != nil {
		return err
	}

	*o = AWSSSOSetupRequest(varAWSSSOSetupRequest)

	return err
}

type NullableAWSSSOSetupRequest struct {
	value *AWSSSOSetupRequest
	isSet bool
}

func (v NullableAWSSSOSetupRequest) Get() *AWSSSOSetupRequest {
	return v.value
}

func (v *NullableAWSSSOSetupRequest) Set(val *AWSSSOSetupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSSSOSetupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSSSOSetupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSSSOSetupRequest(val *AWSSSOSetupRequest) *NullableAWSSSOSetupRequest {
	return &NullableAWSSSOSetupRequest{value: val, isSet: true}
}

func (v NullableAWSSSOSetupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSSSOSetupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


