// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCloudAccountsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCloudAccountsResponse{}

// ListCloudAccountsResponse Response containing list of cloud accounts
type ListCloudAccountsResponse struct {
	// List of cloud accounts/subscriptions
	Accounts []CloudAccount `json:"accounts"`
}

type _ListCloudAccountsResponse ListCloudAccountsResponse

// NewListCloudAccountsResponse instantiates a new ListCloudAccountsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCloudAccountsResponse(accounts []CloudAccount) *ListCloudAccountsResponse {
	this := ListCloudAccountsResponse{}
	this.Accounts = accounts
	return &this
}

// NewListCloudAccountsResponseWithDefaults instantiates a new ListCloudAccountsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCloudAccountsResponseWithDefaults() *ListCloudAccountsResponse {
	this := ListCloudAccountsResponse{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *ListCloudAccountsResponse) GetAccounts() []CloudAccount {
	if o == nil {
		var ret []CloudAccount
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *ListCloudAccountsResponse) GetAccountsOk() ([]CloudAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *ListCloudAccountsResponse) SetAccounts(v []CloudAccount) {
	o.Accounts = v
}

func (o ListCloudAccountsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCloudAccountsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	return toSerialize, nil
}

func (o *ListCloudAccountsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCloudAccountsResponse := _ListCloudAccountsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCloudAccountsResponse)

	if err != nil {
		return err
	}

	*o = ListCloudAccountsResponse(varListCloudAccountsResponse)

	return err
}

type NullableListCloudAccountsResponse struct {
	value *ListCloudAccountsResponse
	isSet bool
}

func (v NullableListCloudAccountsResponse) Get() *ListCloudAccountsResponse {
	return v.value
}

func (v *NullableListCloudAccountsResponse) Set(val *ListCloudAccountsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCloudAccountsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCloudAccountsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCloudAccountsResponse(val *ListCloudAccountsResponse) *NullableListCloudAccountsResponse {
	return &NullableListCloudAccountsResponse{value: val, isSet: true}
}

func (v NullableListCloudAccountsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCloudAccountsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


