// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentReferrerMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentReferrerMetadata{}

// EnvironmentReferrerMetadata EnvironmentReferrerMetadata contains counts of different types of entities that reference an environment.
type EnvironmentReferrerMetadata struct {
	// The number of environments that reference this environment.
	EnvironmentReferrerCount int64 `json:"environmentReferrerCount"`
	// The number of Insights accounts that reference this environment.
	InsightsAccountReferrerCount int64 `json:"insightsAccountReferrerCount"`
	// The number of stacks that reference this environment.
	StackReferrerCount int64 `json:"stackReferrerCount"`
}

type _EnvironmentReferrerMetadata EnvironmentReferrerMetadata

// NewEnvironmentReferrerMetadata instantiates a new EnvironmentReferrerMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentReferrerMetadata(environmentReferrerCount int64, insightsAccountReferrerCount int64, stackReferrerCount int64) *EnvironmentReferrerMetadata {
	this := EnvironmentReferrerMetadata{}
	this.EnvironmentReferrerCount = environmentReferrerCount
	this.InsightsAccountReferrerCount = insightsAccountReferrerCount
	this.StackReferrerCount = stackReferrerCount
	return &this
}

// NewEnvironmentReferrerMetadataWithDefaults instantiates a new EnvironmentReferrerMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentReferrerMetadataWithDefaults() *EnvironmentReferrerMetadata {
	this := EnvironmentReferrerMetadata{}
	return &this
}

// GetEnvironmentReferrerCount returns the EnvironmentReferrerCount field value
func (o *EnvironmentReferrerMetadata) GetEnvironmentReferrerCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EnvironmentReferrerCount
}

// GetEnvironmentReferrerCountOk returns a tuple with the EnvironmentReferrerCount field value
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrerMetadata) GetEnvironmentReferrerCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentReferrerCount, true
}

// SetEnvironmentReferrerCount sets field value
func (o *EnvironmentReferrerMetadata) SetEnvironmentReferrerCount(v int64) {
	o.EnvironmentReferrerCount = v
}

// GetInsightsAccountReferrerCount returns the InsightsAccountReferrerCount field value
func (o *EnvironmentReferrerMetadata) GetInsightsAccountReferrerCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InsightsAccountReferrerCount
}

// GetInsightsAccountReferrerCountOk returns a tuple with the InsightsAccountReferrerCount field value
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrerMetadata) GetInsightsAccountReferrerCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InsightsAccountReferrerCount, true
}

// SetInsightsAccountReferrerCount sets field value
func (o *EnvironmentReferrerMetadata) SetInsightsAccountReferrerCount(v int64) {
	o.InsightsAccountReferrerCount = v
}

// GetStackReferrerCount returns the StackReferrerCount field value
func (o *EnvironmentReferrerMetadata) GetStackReferrerCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StackReferrerCount
}

// GetStackReferrerCountOk returns a tuple with the StackReferrerCount field value
// and a boolean to check if the value has been set.
func (o *EnvironmentReferrerMetadata) GetStackReferrerCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StackReferrerCount, true
}

// SetStackReferrerCount sets field value
func (o *EnvironmentReferrerMetadata) SetStackReferrerCount(v int64) {
	o.StackReferrerCount = v
}

func (o EnvironmentReferrerMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentReferrerMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentReferrerCount"] = o.EnvironmentReferrerCount
	toSerialize["insightsAccountReferrerCount"] = o.InsightsAccountReferrerCount
	toSerialize["stackReferrerCount"] = o.StackReferrerCount
	return toSerialize, nil
}

func (o *EnvironmentReferrerMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentReferrerCount",
		"insightsAccountReferrerCount",
		"stackReferrerCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentReferrerMetadata := _EnvironmentReferrerMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentReferrerMetadata)

	if err != nil {
		return err
	}

	*o = EnvironmentReferrerMetadata(varEnvironmentReferrerMetadata)

	return err
}

type NullableEnvironmentReferrerMetadata struct {
	value *EnvironmentReferrerMetadata
	isSet bool
}

func (v NullableEnvironmentReferrerMetadata) Get() *EnvironmentReferrerMetadata {
	return v.value
}

func (v *NullableEnvironmentReferrerMetadata) Set(val *EnvironmentReferrerMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentReferrerMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentReferrerMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentReferrerMetadata(val *EnvironmentReferrerMetadata) *NullableEnvironmentReferrerMetadata {
	return &NullableEnvironmentReferrerMetadata{value: val, isSet: true}
}

func (v NullableEnvironmentReferrerMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentReferrerMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


