// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenEnvironmentResponse{}

// OpenEnvironmentResponse Response body after opening an environment session.
type OpenEnvironmentResponse struct {
	// Any diagnostics generated when opening the environment.
	Diagnostics []EnvironmentDiagnostic `json:"diagnostics,omitempty"`
	// The unique identifier of the opened environment session.
	Id string `json:"id"`
}

type _OpenEnvironmentResponse OpenEnvironmentResponse

// NewOpenEnvironmentResponse instantiates a new OpenEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenEnvironmentResponse(id string) *OpenEnvironmentResponse {
	this := OpenEnvironmentResponse{}
	this.Id = id
	return &this
}

// NewOpenEnvironmentResponseWithDefaults instantiates a new OpenEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenEnvironmentResponseWithDefaults() *OpenEnvironmentResponse {
	this := OpenEnvironmentResponse{}
	return &this
}

// GetDiagnostics returns the Diagnostics field value if set, zero value otherwise.
func (o *OpenEnvironmentResponse) GetDiagnostics() []EnvironmentDiagnostic {
	if o == nil || IsNil(o.Diagnostics) {
		var ret []EnvironmentDiagnostic
		return ret
	}
	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenEnvironmentResponse) GetDiagnosticsOk() ([]EnvironmentDiagnostic, bool) {
	if o == nil || IsNil(o.Diagnostics) {
		return nil, false
	}
	return o.Diagnostics, true
}

// HasDiagnostics returns a boolean if a field has been set.
func (o *OpenEnvironmentResponse) HasDiagnostics() bool {
	if o != nil && !IsNil(o.Diagnostics) {
		return true
	}

	return false
}

// SetDiagnostics gets a reference to the given []EnvironmentDiagnostic and assigns it to the Diagnostics field.
func (o *OpenEnvironmentResponse) SetDiagnostics(v []EnvironmentDiagnostic) {
	o.Diagnostics = v
}

// GetId returns the Id field value
func (o *OpenEnvironmentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenEnvironmentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenEnvironmentResponse) SetId(v string) {
	o.Id = v
}

func (o OpenEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Diagnostics) {
		toSerialize["diagnostics"] = o.Diagnostics
	}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *OpenEnvironmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenEnvironmentResponse := _OpenEnvironmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenEnvironmentResponse)

	if err != nil {
		return err
	}

	*o = OpenEnvironmentResponse(varOpenEnvironmentResponse)

	return err
}

type NullableOpenEnvironmentResponse struct {
	value *OpenEnvironmentResponse
	isSet bool
}

func (v NullableOpenEnvironmentResponse) Get() *OpenEnvironmentResponse {
	return v.value
}

func (v *NullableOpenEnvironmentResponse) Set(val *OpenEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenEnvironmentResponse(val *OpenEnvironmentResponse) *NullableOpenEnvironmentResponse {
	return &NullableOpenEnvironmentResponse{value: val, isSet: true}
}

func (v NullableOpenEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


