// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloudSetupResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudSetupResource{}

// CloudSetupResource A cloud resource that was created or managed during setup
type CloudSetupResource struct {
	// Error message if the resource operation failed
	Error *string `json:"error,omitempty"`
	// Unique identifier of the resource
	Id string `json:"id"`
	// Name of the resource
	Name string `json:"name"`
	// Additional properties of the resource
	Properties *map[string]string `json:"properties,omitempty"`
	// Status of the resource operation
	Status string `json:"status"`
	// Type of the resource
	Type string `json:"type"`
}

type _CloudSetupResource CloudSetupResource

// NewCloudSetupResource instantiates a new CloudSetupResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudSetupResource(id string, name string, status string, type_ string) *CloudSetupResource {
	this := CloudSetupResource{}
	this.Id = id
	this.Name = name
	this.Status = status
	this.Type = type_
	return &this
}

// NewCloudSetupResourceWithDefaults instantiates a new CloudSetupResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudSetupResourceWithDefaults() *CloudSetupResource {
	this := CloudSetupResource{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CloudSetupResource) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CloudSetupResource) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CloudSetupResource) SetError(v string) {
	o.Error = &v
}

// GetId returns the Id field value
func (o *CloudSetupResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CloudSetupResource) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CloudSetupResource) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudSetupResource) SetName(v string) {
	o.Name = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CloudSetupResource) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CloudSetupResource) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *CloudSetupResource) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetStatus returns the Status field value
func (o *CloudSetupResource) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CloudSetupResource) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *CloudSetupResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CloudSetupResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CloudSetupResource) SetType(v string) {
	o.Type = v
}

func (o CloudSetupResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudSetupResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CloudSetupResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudSetupResource := _CloudSetupResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudSetupResource)

	if err != nil {
		return err
	}

	*o = CloudSetupResource(varCloudSetupResource)

	return err
}

type NullableCloudSetupResource struct {
	value *CloudSetupResource
	isSet bool
}

func (v NullableCloudSetupResource) Get() *CloudSetupResource {
	return v.value
}

func (v *NullableCloudSetupResource) Set(val *CloudSetupResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudSetupResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudSetupResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudSetupResource(val *CloudSetupResource) *NullableCloudSetupResource {
	return &NullableCloudSetupResource{value: val, isSet: true}
}

func (v NullableCloudSetupResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudSetupResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


