// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
)

// checks if the UpdateEnvironmentTagRequestNewTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvironmentTagRequestNewTag{}

// UpdateEnvironmentTagRequestNewTag The new tag name and value to set when updating an environment tag.
type UpdateEnvironmentTagRequestNewTag struct {
	// The new tag name.
	Name *string `json:"name,omitempty"`
	// The new tag value.
	Value *string `json:"value,omitempty"`
}

// NewUpdateEnvironmentTagRequestNewTag instantiates a new UpdateEnvironmentTagRequestNewTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentTagRequestNewTag() *UpdateEnvironmentTagRequestNewTag {
	this := UpdateEnvironmentTagRequestNewTag{}
	return &this
}

// NewUpdateEnvironmentTagRequestNewTagWithDefaults instantiates a new UpdateEnvironmentTagRequestNewTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvironmentTagRequestNewTagWithDefaults() *UpdateEnvironmentTagRequestNewTag {
	this := UpdateEnvironmentTagRequestNewTag{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEnvironmentTagRequestNewTag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentTagRequestNewTag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEnvironmentTagRequestNewTag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEnvironmentTagRequestNewTag) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateEnvironmentTagRequestNewTag) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentTagRequestNewTag) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateEnvironmentTagRequestNewTag) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpdateEnvironmentTagRequestNewTag) SetValue(v string) {
	o.Value = &v
}

func (o UpdateEnvironmentTagRequestNewTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvironmentTagRequestNewTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableUpdateEnvironmentTagRequestNewTag struct {
	value *UpdateEnvironmentTagRequestNewTag
	isSet bool
}

func (v NullableUpdateEnvironmentTagRequestNewTag) Get() *UpdateEnvironmentTagRequestNewTag {
	return v.value
}

func (v *NullableUpdateEnvironmentTagRequestNewTag) Set(val *UpdateEnvironmentTagRequestNewTag) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvironmentTagRequestNewTag) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvironmentTagRequestNewTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvironmentTagRequestNewTag(val *UpdateEnvironmentTagRequestNewTag) *NullableUpdateEnvironmentTagRequestNewTag {
	return &NullableUpdateEnvironmentTagRequestNewTag{value: val, isSet: true}
}

func (v NullableUpdateEnvironmentTagRequestNewTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvironmentTagRequestNewTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


