// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateEnvironmentRequest{}

// RotateEnvironmentRequest Request to rotate secrets in an environment.
type RotateEnvironmentRequest struct {
	// The paths of the secrets to rotate.
	Paths []string `json:"paths"`
}

type _RotateEnvironmentRequest RotateEnvironmentRequest

// NewRotateEnvironmentRequest instantiates a new RotateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateEnvironmentRequest(paths []string) *RotateEnvironmentRequest {
	this := RotateEnvironmentRequest{}
	this.Paths = paths
	return &this
}

// NewRotateEnvironmentRequestWithDefaults instantiates a new RotateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateEnvironmentRequestWithDefaults() *RotateEnvironmentRequest {
	this := RotateEnvironmentRequest{}
	return &this
}

// GetPaths returns the Paths field value
func (o *RotateEnvironmentRequest) GetPaths() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Paths
}

// GetPathsOk returns a tuple with the Paths field value
// and a boolean to check if the value has been set.
func (o *RotateEnvironmentRequest) GetPathsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Paths, true
}

// SetPaths sets field value
func (o *RotateEnvironmentRequest) SetPaths(v []string) {
	o.Paths = v
}

func (o RotateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paths"] = o.Paths
	return toSerialize, nil
}

func (o *RotateEnvironmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paths",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateEnvironmentRequest := _RotateEnvironmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateEnvironmentRequest)

	if err != nil {
		return err
	}

	*o = RotateEnvironmentRequest(varRotateEnvironmentRequest)

	return err
}

type NullableRotateEnvironmentRequest struct {
	value *RotateEnvironmentRequest
	isSet bool
}

func (v NullableRotateEnvironmentRequest) Get() *RotateEnvironmentRequest {
	return v.value
}

func (v *NullableRotateEnvironmentRequest) Set(val *RotateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateEnvironmentRequest(val *RotateEnvironmentRequest) *NullableRotateEnvironmentRequest {
	return &NullableRotateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableRotateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


