// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentInsightsAccountReferrer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentInsightsAccountReferrer{}

// EnvironmentInsightsAccountReferrer An EnvironmentInsightsAccountReferrer represents a reference from an Insights account.
type EnvironmentInsightsAccountReferrer struct {
	// The name of the Insights account that references the environment.
	AccountName string `json:"accountName"`
}

type _EnvironmentInsightsAccountReferrer EnvironmentInsightsAccountReferrer

// NewEnvironmentInsightsAccountReferrer instantiates a new EnvironmentInsightsAccountReferrer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentInsightsAccountReferrer(accountName string) *EnvironmentInsightsAccountReferrer {
	this := EnvironmentInsightsAccountReferrer{}
	this.AccountName = accountName
	return &this
}

// NewEnvironmentInsightsAccountReferrerWithDefaults instantiates a new EnvironmentInsightsAccountReferrer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentInsightsAccountReferrerWithDefaults() *EnvironmentInsightsAccountReferrer {
	this := EnvironmentInsightsAccountReferrer{}
	return &this
}

// GetAccountName returns the AccountName field value
func (o *EnvironmentInsightsAccountReferrer) GetAccountName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value
// and a boolean to check if the value has been set.
func (o *EnvironmentInsightsAccountReferrer) GetAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountName, true
}

// SetAccountName sets field value
func (o *EnvironmentInsightsAccountReferrer) SetAccountName(v string) {
	o.AccountName = v
}

func (o EnvironmentInsightsAccountReferrer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentInsightsAccountReferrer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountName"] = o.AccountName
	return toSerialize, nil
}

func (o *EnvironmentInsightsAccountReferrer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentInsightsAccountReferrer := _EnvironmentInsightsAccountReferrer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentInsightsAccountReferrer)

	if err != nil {
		return err
	}

	*o = EnvironmentInsightsAccountReferrer(varEnvironmentInsightsAccountReferrer)

	return err
}

type NullableEnvironmentInsightsAccountReferrer struct {
	value *EnvironmentInsightsAccountReferrer
	isSet bool
}

func (v NullableEnvironmentInsightsAccountReferrer) Get() *EnvironmentInsightsAccountReferrer {
	return v.value
}

func (v *NullableEnvironmentInsightsAccountReferrer) Set(val *EnvironmentInsightsAccountReferrer) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentInsightsAccountReferrer) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentInsightsAccountReferrer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentInsightsAccountReferrer(val *EnvironmentInsightsAccountReferrer) *NullableEnvironmentInsightsAccountReferrer {
	return &NullableEnvironmentInsightsAccountReferrer{value: val, isSet: true}
}

func (v NullableEnvironmentInsightsAccountReferrer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentInsightsAccountReferrer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


