// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esc_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListEnvironmentTagsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEnvironmentTagsResponse{}

// ListEnvironmentTagsResponse Response containing a map of environment tags.
type ListEnvironmentTagsResponse struct {
	// Token for fetching the next page of results
	NextToken string `json:"nextToken"`
	// Map of tag names to their tag details
	Tags map[string]EnvironmentTag `json:"tags"`
}

type _ListEnvironmentTagsResponse ListEnvironmentTagsResponse

// NewListEnvironmentTagsResponse instantiates a new ListEnvironmentTagsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEnvironmentTagsResponse(nextToken string, tags map[string]EnvironmentTag) *ListEnvironmentTagsResponse {
	this := ListEnvironmentTagsResponse{}
	this.NextToken = nextToken
	this.Tags = tags
	return &this
}

// NewListEnvironmentTagsResponseWithDefaults instantiates a new ListEnvironmentTagsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEnvironmentTagsResponseWithDefaults() *ListEnvironmentTagsResponse {
	this := ListEnvironmentTagsResponse{}
	return &this
}

// GetNextToken returns the NextToken field value
func (o *ListEnvironmentTagsResponse) GetNextToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentTagsResponse) GetNextTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextToken, true
}

// SetNextToken sets field value
func (o *ListEnvironmentTagsResponse) SetNextToken(v string) {
	o.NextToken = v
}

// GetTags returns the Tags field value
func (o *ListEnvironmentTagsResponse) GetTags() map[string]EnvironmentTag {
	if o == nil {
		var ret map[string]EnvironmentTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentTagsResponse) GetTagsOk() (*map[string]EnvironmentTag, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *ListEnvironmentTagsResponse) SetTags(v map[string]EnvironmentTag) {
	o.Tags = v
}

func (o ListEnvironmentTagsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEnvironmentTagsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextToken"] = o.NextToken
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *ListEnvironmentTagsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nextToken",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEnvironmentTagsResponse := _ListEnvironmentTagsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListEnvironmentTagsResponse)

	if err != nil {
		return err
	}

	*o = ListEnvironmentTagsResponse(varListEnvironmentTagsResponse)

	return err
}

type NullableListEnvironmentTagsResponse struct {
	value *ListEnvironmentTagsResponse
	isSet bool
}

func (v NullableListEnvironmentTagsResponse) Get() *ListEnvironmentTagsResponse {
	return v.value
}

func (v *NullableListEnvironmentTagsResponse) Set(val *ListEnvironmentTagsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListEnvironmentTagsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListEnvironmentTagsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEnvironmentTagsResponse(val *ListEnvironmentTagsResponse) *NullableListEnvironmentTagsResponse {
	return &NullableListEnvironmentTagsResponse{value: val, isSet: true}
}

func (v NullableListEnvironmentTagsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEnvironmentTagsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


