# coding: utf-8

# Copyright 2024, Pulumi Corporation.  All rights reserved.

"""
    ESC (Environments, Secrets, Config) API

    Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class AWSSetupRequest(BaseModel):
    """
    Request to setup AWS OIDC infrastructure using static credentials
    """ # noqa: E501
    access_key_id: StrictStr = Field(description="AWS Access Key ID", alias="accessKeyId")
    oidc_role_name: StrictStr = Field(description="Name of IAM Role for OIDC", alias="oidcRoleName")
    policy_arn: StrictStr = Field(description="ARN of the IAM policy to attach to the role", alias="policyArn")
    secret_access_key: StrictStr = Field(description="AWS Secret Access Key", alias="secretAccessKey")
    session_token: StrictStr = Field(description="AWS Session Token (for temporary credentials)", alias="sessionToken")
    __properties: ClassVar[List[str]] = ["accessKeyId", "oidcRoleName", "policyArn", "secretAccessKey", "sessionToken"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AWSSetupRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AWSSetupRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessKeyId": obj.get("accessKeyId"),
            "oidcRoleName": obj.get("oidcRoleName"),
            "policyArn": obj.get("policyArn"),
            "secretAccessKey": obj.get("secretAccessKey"),
            "sessionToken": obj.get("sessionToken")
        })
        return _obj


