# coding: utf-8

# Copyright 2024, Pulumi Corporation.  All rights reserved.

"""
    ESC (Environments, Secrets, Config) API

    Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EnvironmentRevisionRetracted(BaseModel):
    """
    EnvironmentRevisionRetracted contains information about a retracted environment revision.
    """ # noqa: E501
    at: datetime = Field(description="The timestamp when the revision was retracted.")
    by_login: Optional[StrictStr] = Field(default=None, description="The login name of the user who retracted the revision.", alias="byLogin")
    by_name: Optional[StrictStr] = Field(default=None, description="The display name of the user who retracted the revision.", alias="byName")
    reason: Optional[StrictStr] = Field(default=None, description="The reason the revision was retracted.")
    replacement: StrictInt = Field(description="The revision number that replaced this retracted revision.")
    __properties: ClassVar[List[str]] = ["at", "byLogin", "byName", "reason", "replacement"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnvironmentRevisionRetracted from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnvironmentRevisionRetracted from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "at": obj.get("at"),
            "byLogin": obj.get("byLogin"),
            "byName": obj.get("byName"),
            "reason": obj.get("reason"),
            "replacement": obj.get("replacement")
        })
        return _obj


