# coding: utf-8

# Copyright 2024, Pulumi Corporation.  All rights reserved.

"""
    ESC (Environments, Secrets, Config) API

    Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from pulumi_esc_sdk.models.esc_access_expr import EscAccessExpr
from pulumi_esc_sdk.models.esc_interpolation import EscInterpolation
from pulumi_esc_sdk.models.esc_property_accessor import EscPropertyAccessor
from pulumi_esc_sdk.models.esc_range import EscRange
from typing import Optional, Set
from typing_extensions import Self

class EscExpr(BaseModel):
    """
    An Expr holds information about an expression in an environment definition.
    """ # noqa: E501
    access: Optional[EscAccessExpr] = None
    base: Optional[EscExpr] = None
    builtin: Optional[EscBuiltinExpr] = None
    interpolate: Optional[List[EscInterpolation]] = Field(default=None, description="The interpolations, if this is a string interpolation expression.")
    key_ranges: Optional[Dict[str, EscRange]] = Field(default=None, description="Ranges for the object's keys, if this is an object expression.", alias="keyRanges")
    list: Optional[List[EscExpr]] = Field(default=None, description="The list elements, if this is a list expression.")
    literal: Optional[Any] = Field(default=None, description="The literal value, if this is a literal expression (nil, bool, json.Number, or string)")
    object: Optional[Dict[str, EscExpr]] = Field(default=None, description="The object properties, if this is an object expression.")
    range: EscRange
    var_schema: Optional[Any] = Field(default=None, description="The schema of the expression's result.", alias="schema")
    symbol: Optional[List[EscPropertyAccessor]] = Field(default=None, description="The property accessors, if this is a symbol expression.")
    __properties: ClassVar[List[str]] = ["access", "base", "builtin", "interpolate", "keyRanges", "list", "literal", "object", "range", "schema", "symbol"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EscExpr from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access
        if self.access:
            _dict['access'] = self.access.to_dict()
        # override the default output from pydantic by calling `to_dict()` of base
        if self.base:
            _dict['base'] = self.base.to_dict()
        # override the default output from pydantic by calling `to_dict()` of builtin
        if self.builtin:
            _dict['builtin'] = self.builtin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in interpolate (list)
        _items = []
        if self.interpolate:
            for _item in self.interpolate:
                if _item:
                    _items.append(_item.to_dict())
            _dict['interpolate'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in key_ranges (dict)
        _field_dict = {}
        if self.key_ranges:
            for _key in self.key_ranges:
                if self.key_ranges[_key]:
                    _field_dict[_key] = self.key_ranges[_key].to_dict()
            _dict['keyRanges'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in list (list)
        _items = []
        if self.list:
            for _item in self.list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['list'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in object (dict)
        _field_dict = {}
        if self.object:
            for _key in self.object:
                if self.object[_key]:
                    _field_dict[_key] = self.object[_key].to_dict()
            _dict['object'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of range
        if self.range:
            _dict['range'] = self.range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in symbol (list)
        _items = []
        if self.symbol:
            for _item in self.symbol:
                if _item:
                    _items.append(_item.to_dict())
            _dict['symbol'] = _items
        # set to None if literal (nullable) is None
        # and model_fields_set contains the field
        if self.literal is None and "literal" in self.model_fields_set:
            _dict['literal'] = None

        # set to None if var_schema (nullable) is None
        # and model_fields_set contains the field
        if self.var_schema is None and "var_schema" in self.model_fields_set:
            _dict['schema'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EscExpr from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access": EscAccessExpr.from_dict(obj["access"]) if obj.get("access") is not None else None,
            "base": EscExpr.from_dict(obj["base"]) if obj.get("base") is not None else None,
            "builtin": EscBuiltinExpr.from_dict(obj["builtin"]) if obj.get("builtin") is not None else None,
            "interpolate": [EscInterpolation.from_dict(_item) for _item in obj["interpolate"]] if obj.get("interpolate") is not None else None,
            "keyRanges": dict(
                (_k, EscRange.from_dict(_v))
                for _k, _v in obj["keyRanges"].items()
            )
            if obj.get("keyRanges") is not None
            else None,
            "list": [EscExpr.from_dict(_item) for _item in obj["list"]] if obj.get("list") is not None else None,
            "literal": obj.get("literal"),
            "object": dict(
                (_k, EscExpr.from_dict(_v))
                for _k, _v in obj["object"].items()
            )
            if obj.get("object") is not None
            else None,
            "range": EscRange.from_dict(obj["range"]) if obj.get("range") is not None else None,
            "schema": obj.get("schema"),
            "symbol": [EscPropertyAccessor.from_dict(_item) for _item in obj["symbol"]] if obj.get("symbol") is not None else None
        })
        return _obj

from pulumi_esc_sdk.models.esc_builtin_expr import EscBuiltinExpr
# TODO: Rewrite to not use raise_errors
EscExpr.model_rebuild(raise_errors=False)

