# coding: utf-8

# Copyright 2024, Pulumi Corporation.  All rights reserved.

"""
    ESC (Environments, Secrets, Config) API

    Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pulumi_esc_sdk.models.environment_links import EnvironmentLinks
from pulumi_esc_sdk.models.environment_referrer_metadata import EnvironmentReferrerMetadata
from pulumi_esc_sdk.models.environment_settings import EnvironmentSettings
from typing import Optional, Set
from typing_extensions import Self

class OrgEnvironment(BaseModel):
    """
    OrgEnvironment represents an environment within an organization.
    """ # noqa: E501
    created: StrictStr = Field(description="The ISO 8601 timestamp when the environment was created.")
    deleted_at: Optional[StrictStr] = Field(default=None, description="The ISO 8601 timestamp when the environment was soft-deleted, or null if not deleted.", alias="deletedAt")
    id: StrictStr = Field(description="The unique identifier of the environment.")
    links: Optional[EnvironmentLinks] = None
    modified: StrictStr = Field(description="The ISO 8601 timestamp when the environment was last modified.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the environment.")
    organization: Optional[StrictStr] = Field(default=None, description="The login name of the organization that owns this environment.")
    project: Optional[StrictStr] = Field(default=None, description="The project name that contains this environment, if project-scoped.")
    referrer_metadata: EnvironmentReferrerMetadata = Field(alias="referrerMetadata")
    settings: EnvironmentSettings
    tags: Dict[str, StrictStr] = Field(description="User-defined key-value tags associated with the environment for organization and filtering.")
    __properties: ClassVar[List[str]] = ["created", "deletedAt", "id", "links", "modified", "name", "organization", "project", "referrerMetadata", "settings", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrgEnvironment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of referrer_metadata
        if self.referrer_metadata:
            _dict['referrerMetadata'] = self.referrer_metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrgEnvironment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "deletedAt": obj.get("deletedAt"),
            "id": obj.get("id"),
            "links": EnvironmentLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "modified": obj.get("modified"),
            "name": obj.get("name"),
            "organization": obj.get("organization"),
            "project": obj.get("project"),
            "referrerMetadata": EnvironmentReferrerMetadata.from_dict(obj["referrerMetadata"]) if obj.get("referrerMetadata") is not None else None,
            "settings": EnvironmentSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "tags": obj.get("tags")
        })
        return _obj


