permissions: write-all # Equivalent to default permissions plus id-token: write
name: Publish Prerelease

on:
  push:
    tags:
      - v*.*.*-**

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

jobs:
  lint:
    uses: ./.github/workflows/stage-lint.yml
  test:
    uses: ./.github/workflows/stage-test.yml
    with:
      enable-coverage: true
    secrets: inherit

  publish-sdks:
    needs: [test, lint]
    uses: ./.github/workflows/stage-publish-sdk.yml
    with:
      version: ${{ github.ref_name }}
      prerelease: true
    secrets: inherit
