name: Test

on:
  workflow_call:
    inputs:
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ''
        required: false
        type: string

      enable-coverage:
        description: Collects coverage data from tests.
        default: false
        required: false
        type: boolean

env:
  PULUMI_ORG: moolumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_PRODUCTION }}

jobs:
  test_go:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commit-ref }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: ${{ matrix.go-stable }}
      - name: Test w/coverage
        if: ${{ inputs.enable-coverage }}
        run: make test_cover
      - name: Test
        if: ${{ ! inputs.enable-coverage }}
        run: make test
      - name: Upload code coverage
        if: ${{ inputs.enable-coverage }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x]
        go-stable: [true]
  test_typescript:
    name: Test Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commit-ref }}      

      - name: Run tests
        run: cd sdk/typescript && npm i && npm run test
        